// M6b "Sagas": the voice's keys of wisdom, faith and conflict (proverb saying omen curse threat insult grief doubt
// warning boast refusal surprise). VOICE lane. The block format and the rules: voice.cpp; the eight idioms:
// voice_social.cpp. Proverbs: 13 per people. Sayings speak the people's faith and name its first god ({GIVER.GOD}).
// Proverbs of public-domain traditions (the Norse hall, the steppe's bundle of arrows, the sages' spilled water) are
// retold freely; nothing is taken from modern works.
#include <vector>

namespace story {
namespace saga {
namespace voicedata {

namespace {

const char* const kProverb = R"VOICE(
= proverb
A0 AS THEY SAY,
A0 MY MOTHER USED TO SAY IT:
B0 A LIE RUNS FAST, BUT IT RUNS IN CIRCLES.
B0 SMOKE ALWAYS FINDS THE CHIMNEY.
B0 THE WELL KNOWS WHO DRINKS AT NIGHT.
B0 A SHUT MOUTH CATCHES NO FLIES.
B0 YOU CAN'T UNRING A BELL.
B0 EVERY ROAD HAS TWO ENDS.
B0 BORROWED BOOTS PINCH THE WORST.
B0 A DRY YEAR TEACHES WHAT A WET ONE WON'T.
B0 SPILT MILK FEEDS THE CAT.
B0 THE FIRST STONE IS THE HEAVIEST.
B0 A FOOL'S PURSE HAS A HOLE IN IT.
B0 STILL DOGS BITE DEEPEST.
B0 THE PATCH IS UGLIER THAN THE HOLE.
A1 AS THE OLD ONES SAY,
A1 WE {GIVER.PEOPLE} SAY:
B1 THE SEA GIVES, AND THE SEA COUNTS.
B1 COLD HANDS, HONEST HANDS.
B1 PRAISE THE ICE WHEN YOU ARE ACROSS IT.
B1 A NAME OUTLIVES THE BONE-HOUSE.
B1 THE WOLF THAT WAITS EATS.
B1 FEW ARE THE FRIENDS AT THE FEAST'S END.
B1 THE WAVE DOES NOT ASK THE SHIP.
B1 SHORT IS THE DAY OF THE OATH-BREAKER.
B1 A SPLIT HALL BURNS FIRST.
B1 THE MEAD-HORN LOOSENS EVERY TONGUE.
B1 FROST TELLS THE TRUTH ABOUT A ROOF.
B1 BETTER A HUT OF YOUR OWN THAN A KING'S BENCH.
B1 CATTLE DIE, KIN DIE; THE NAME DOES NOT.
A2 AS MY GRAN SAID,
A2 WE SAY IN {HOME}:
B2 YOU CAN'T EAT THE SEED CORN.
B2 A WARM HEARTH HIDES A COLD CELLAR.
B2 THE MILL WON'T GRIND WITH WATER GONE BY.
B2 BREAD SHARED IS TWICE THE BREAD.
B2 THE FOX IS ALWAYS SORRY AFTER THE HENS.
B2 A BARE FIELD IN SPRING IS A BARE TABLE IN WINTER.
B2 NEVER BUY A HORSE ON MARKET DAY.
B2 THE KETTLE'S LOUDEST JUST BEFORE IT BOILS.
B2 A GOOD FENCE NEEDS TWO NEIGHBOURS.
B2 THE PLOUGH DOESN'T ASK WHO HOLDS IT.
B2 WHAT THE FROST TAKES, THE SPRING DOESN'T OWE.
B2 THE LANDLORD'S CAT IS ALWAYS FAT.
B2 EVERY HARVEST HAS ITS RATS.
A3 AS THE CARAVANS SAY,
A3 IT IS WRITTEN ON THE WELL-STONES:
B3 THE GUEST WHO EATS YOUR SALT IS YOUR KIN.
B3 A WELL IS WORTH MORE THAN A KING.
B3 PRAISE THE STARS, BUT HOBBLE THE CAMEL.
B3 THE SAND REMEMBERS NO FOOTPRINT.
B3 THIRST MAKES HONEST FOLK OF US ALL.
B3 THE PATIENT CARAVAN REACHES THE WELL.
B3 THE GRANDFATHER PLANTS THE SHADE TREE.
B3 THE SUN SEES WHAT THE NIGHT HIDES.
B3 ONE DATE SHARED IS SWEETER THAN TEN EATEN.
B3 A SCORPION DOES NOT CHANGE IN THE SHADE.
B3 WHO DIGS A WELL FOR OTHERS DRINKS FIRST.
B3 THE DUNE MOVES, BUT THE STAR STAYS.
B3 DO NOT SELL THE WATER BEFORE THE WELL.
A4 THE OLD RIDERS SAY:
A4 AS WE {GIVER.PEOPLE} SAY,
B4 THE SKY IS WIDE. THE HORSE IS ONE.
B4 ONE ARROW SNAPS; A BUNDLE HOLDS.
B4 THE GRASS BENDS; THE GRASS LIVES.
B4 COUNT THE HERD IN SPRING, NOT IN AUTUMN.
B4 A HORSE IS KNOWN ON THE LONG ROAD.
B4 THE WIND DOES NOT WAIT FOR THE SLOW.
B4 WHERE THE GRASS IS, THERE IS HOME.
B4 THE WOLF HUNTS THE LAST HORSE.
B4 SMOKE ON THE HORIZON IS NEVER GOOD NEWS.
B4 A SHORT TONGUE KEEPS A LONG LIFE.
B4 THE FALCON DOES NOT TALK OF THE HUNT.
B4 BETTER A LAME HORSE THAN A PROUD FOOT.
B4 THE STEPPE FORGIVES NOTHING AND FORGETS ALL.
A5 AS THE FERRYMEN SAY,
A5 WE SAY ON THE WATER:
B5 STILL WATER HIDES THE DEEPEST EELS.
B5 THE RIVER FORGIVES, BUT IT DOESN'T FORGET.
B5 DON'T TRUST A PLANK YOU DIDN'T NAIL.
B5 THE FOG DOESN'T LIE. IT JUST HIDES THE TRUTH.
B5 EVERY TIDE COMES BACK FOR SOMETHING.
B5 A HERON STANDS STILL AND EATS WELL.
B5 MUD WASHES OFF. SHAME SOAKS IN.
B5 THE REED BENDS AND OUTLIVES THE OAK.
B5 WHAT THE FLOOD TAKES, THE MUD KEEPS.
B5 NEVER LAUGH AT A SINKING BOAT.
B5 THE EEL YOU LOST WAS ALWAYS THE BIGGEST.
B5 SLOW WATER CARVES THE DEEPEST BANK.
B5 DRY FEET MAKE A SHORT MEMORY.
A6 THE SAGES TEACH:
A6 AS OUR ANCESTORS SAID,
B6 THE NAIL THAT STANDS UP IS HAMMERED DOWN.
B6 A FAMILY'S NAME IS WOVEN, NOT BOUGHT.
B6 WATER POURED OUT CANNOT BE GATHERED.
B6 THE BAMBOO BENDS, BUT IT DOES NOT BREAK.
B6 ONE WHO LOSES FACE LOSES ALL.
B6 THE LANTERN DOES NOT LIGHT ITS OWN BASE.
B6 THE THOUSAND-STEP ROAD BEGINS AT THE GATE.
B6 THE INK OF THE ANCESTORS DOES NOT FADE.
B6 A GUEST'S RUDENESS SHAMES THE HOST.
B6 ONLY THE STILL POND SHOWS THE MOON.
B6 HEAVEN IS HIGH AND THE MAGISTRATE IS FAR.
B6 THE TEA REMEMBERS THE HAND THAT POURED IT.
B6 THE CARP THAT LEAPS THE GATE BECOMES A DRAGON.
A7 THE ELDEST TREES SAY:
A7 AS WE {GIVER.PEOPLE} SING,
B7 THE OAK WAS ONCE A NUT THAT HELD ITS GROUND.
B7 STARS DO NOT HURRY, YET THEY ARRIVE.
B7 WHAT THE ROOT KNOWS, THE LEAF FORGETS.
B7 A SONG SUNG ONCE IS SUNG FOREVER.
B7 EVERY FALLEN LEAF FEEDS THE TREE.
B7 THE MOON KEEPS WHAT THE SUN BURNS AWAY.
B7 BRANCHES FIGHT; ROOTS EMBRACE.
B7 THE WOOD IS QUIET WHERE THE WOLF WALKS.
B7 THE SAPLING THINKS THE STORM IS ITS OWN.
B7 NO STAR IS LOST; IT IS ONLY FAR.
B7 MOSS GROWS ON THE PATIENT STONE.
B7 THE STREAM SINGS ONLY WHERE IT STUMBLES.
B7 CUT ONE TREE, PLANT THREE.
)VOICE";

const char* const kSaying = R"VOICE(
= saying
A0 IT IS WRITTEN:
A0 THE PRIESTS SAY IT:
B0 WHAT IS SOWN IN THE DARK IS REAPED IN THE LIGHT.
B0 {GIVER.GOD} WEIGHS THE HEART, NOT THE PURSE.
B0 THE PROUD STAND TALL, AND FALL FARTHER.
B0 EVERY DEBT IS PAID, IN THIS LIFE OR AFTER.
B0 {GIVER.GOD} KNOWS THE NAME OF EVERY STRANGER.
B0 THE LAST SHALL EAT AT THE FIRST TABLE.
B0 A GATE SHUT ON THE POOR IS SHUT ON {GIVER.GOD}.
B0 MERCY GIVEN COMES BACK DOUBLED.
A1 THE SKALDS OF {GIVER.GOD} SAY:
A1 AS IT IS SUNG,
B1 {GIVER.GOD} WEIGHS THE OATH, NOT THE OATH-TAKER.
B1 THE BRAVE DIE ONCE; THE OATH-BREAKER DAILY.
B1 AT THE WORLD'S END, ONLY DEEDS ARE COUNTED.
B1 THE HALL OF {GIVER.GOD} HAS NO SEAT FOR COWARDS.
B1 WHAT IS SWORN ON THE RING, {GIVER.GOD} HEARS.
B1 THE COLD IS A TEACHER, AND {GIVER.GOD} ITS MASTER.
B1 NONE CUTS THE THREAD THAT {GIVER.GOD} SPINS.
B1 THE FIRE OF THE HEARTH IS THE FIRE OF {GIVER.GOD}.
A2 THE GOOD BOOK SAYS:
A2 AS THE PRIEST TELLS IT,
B2 AS YOU SOW, SO SHALL YOU REAP.
B2 {GIVER.GOD} FEEDS THE SPARROW AND THE KING ALIKE.
B2 THE HUMBLE FIELD BEARS THE FULLEST EAR.
B2 A SHARED LOAF IS AN OFFERING TO {GIVER.GOD}.
B2 THE GLEANINGS BELONG TO THE POOR.
B2 {GIVER.GOD} KEEPS THE BOOK OF EVERY HARVEST.
B2 FIRST FRUITS TO {GIVER.GOD}, THE REST TO THE TABLE.
B2 WHO SHUTS OUT A STRANGER SHUTS OUT {GIVER.GOD}.
A3 THE SUN-PRIESTS TEACH:
A3 IT IS WRITTEN IN GOLD:
B3 THE SUN SEES ALL, AND {GIVER.GOD} REMEMBERS.
B3 HONOUR THE GUEST, FOR {GIVER.GOD} SENT THEM.
B3 NO SHADOW HIDES FROM THE NOON OF {GIVER.GOD}.
B3 WATER GIVEN IS A PRAYER ANSWERED.
B3 {GIVER.GOD} COUNTS THE GRAINS AND THE DAYS.
B3 THE LIAR'S WELL RUNS SALT.
B3 AT DUSK, EVERY DEBT IS WEIGHED.
B3 THE STARS ARE THE LAMPS OF THE PATIENT.
A4 THE SHAMANS SAY:
A4 UNDER THE WIDE SKY,
B4 {GIVER.GOD} SEES THE WHOLE STEPPE AT ONCE.
B4 THE SKY GIVES RAIN TO THE JUST AND THE THIEF.
B4 WHAT IS SPILLED ON THE GRASS RETURNS TO {GIVER.GOD}.
B4 THE DEAD RIDE ON, BEYOND THE LAST HILL.
B4 THE WIND CARRIES EVERY WORD TO {GIVER.GOD}.
B4 A BROKEN OATH LAMES THE HORSE OF THE SOUL.
B4 {GIVER.GOD} DOES NOT LOVE THE ONE WHO HOARDS.
B4 THE SKY HAS NO WALLS, AND NO HIDING.
A5 THE RIVER-PRIESTS SAY:
A5 AS THE WATER TEACHES,
B5 ALL WATER GOES HOME TO {GIVER.GOD} AT LAST.
B5 THE RIVER CARRIES THE GUILTY DOWN FIRST.
B5 WHAT YOU THROW IN THE WATER, {GIVER.GOD} KEEPS.
B5 THE FLOOD IS A JUDGE THAT TAKES NO BRIBE.
B5 {GIVER.GOD} SITS WHERE THE RIVERS MEET.
B5 THE DROWNED ARE NOT LOST. THEY ARE KEPT.
B5 MUDDY WATER CLEARS IF YOU LEAVE IT BE.
B5 EVEN THE RIVER RETURNS TO THE SEA.
A6 THE CLASSICS TEACH:
A6 THE ANCESTORS INSTRUCT:
B6 THE MANDATE OF HEAVEN PASSES FROM THE UNJUST.
B6 THE ANCESTORS KEEP THE LEDGER OF HEAVEN.
B6 THE DUTIFUL CHILD IS THE PILLAR OF THE HOUSE.
B6 PROPRIETY IS THE ROOF; KINDNESS THE BEAM.
B6 {GIVER.GOD} WATCHES THE HUMBLE AND THE HIGH ALIKE.
B6 WHO HONOURS THE DEAD IS HONOURED BY THEM.
B6 THE RIGHT WORD IN THE RIGHT HOUR IS JADE.
B6 HEAVEN DOES NOT SPEAK; IT ACTS.
A7 THE STAR-SONGS SAY:
A7 AS THE ELDERS SING,
B7 {GIVER.GOD} WROTE OUR NAMES IN THE STARS.
B7 ALL THAT FALLS RISES AGAIN IN SPRING.
B7 THE STARS KEEP ACCOUNT, AND THEY ARE PATIENT.
B7 THE OLDEST TREE REMEMBERS THE FIRST SONG.
B7 NO LEAF FALLS UNSEEN BY {GIVER.GOD}.
B7 LIGHT DOES NOT ASK THE DARK FOR LEAVE.
B7 WHAT IS PLANTED IN GRIEF IS REAPED IN SONG.
B7 THE ROOT AND THE STAR ARE ONE LIGHT.
)VOICE";

const char* const kOmen = R"VOICE(
= omen
F0 THE CROWS FLEW EAST THIS MORNING.
F0 THE WELL WATER TASTED OF IRON.
F0 THE DOGS WOULDN'T STOP HOWLING.
A0 I SAW A SIGN.
A0 MARK THIS:
A0 THERE WAS A SIGN.
B0 A HARE CROSSED MY PATH TWICE.
B0 THE CANDLE BURNED BLUE.
B0 A WHITE BIRD SAT ON THE ROOF.
F1 A RAVEN SAT ON THE PROW AND WOULD NOT LEAVE.
F1 THE SKY-LIGHTS BURNED RED LAST NIGHT.
F1 MY HORN CRACKED IN THE COLD. AN OLD SIGN.
A1 THE GODS SPEAK:
A1 A SIGN:
A1 I SAW IT:
B1 THE WAVES RAN BACKWARDS.
B1 A WOLF HOWLED AT NOON.
B1 THE ICE SANG ALL NIGHT.
F2 THE MILK CURDLED IN THE PAIL.
F2 A ROBIN FLEW INTO THE HOUSE.
F2 THE BREAD WOULDN'T RISE THREE DAYS RUNNING.
A2 MARK MY WORDS,
A2 A BAD SIGN:
A2 IT'S A SIGN.
B2 THE CART WHEEL CRACKED ON A FEAST DAY.
B2 THE HENS STOPPED LAYING.
B2 THE CATTLE LAY DOWN AT NOON.
F3 A FALLING STAR CROSSED THE SUN'S PATH.
F3 THE SAND HISSED WITH NO WIND.
F3 A SCORPION DANCED ON THE WELL-STONE.
A3 THE STARS SPEAK:
A3 A SIGN, BY THE SUN:
A3 I SAW IT WRITTEN:
B3 THE WELL WATER RAN RED.
B3 THE CAMELS WOULD NOT KNEEL.
B3 AN OWL CALLED IN THE NOON HEAT.
F4 A HAWK DROPPED ITS KILL AT MY FEET.
F4 THE HORSES FACED WEST ALL NIGHT.
F4 THE GRASS BURNED WHERE NO FIRE WAS.
A4 A SIGN.
A4 THE SKY SAYS:
A4 I SAW:
B4 THE WIND SPOKE IN TWO VOICES.
B4 A WHITE MARE FOALED A BLACK COLT.
B4 THE SKY WENT GREEN AT DUSK.
F5 THE EELS SWAM UPSTREAM. THEY NEVER DO.
F5 THE FOG CAME IN AGAINST THE WIND.
F5 A HERON STOOD ON MY ROOF ALL NIGHT.
A5 A SIGN ON THE WATER:
A5 THE RIVER SAYS:
A5 I SAW IT FROM THE BOAT:
B5 THE FROGS WENT SILENT AT ONCE.
B5 THE WATER RAN BACKWARDS AN HOUR.
B5 THE NETS CAME UP FULL OF BLACK WEED.
F6 THE INCENSE SMOKE FELL INSTEAD OF RISING.
F6 A CRACK APPEARED ON THE ANCESTOR TABLET.
F6 THE CARP IN THE TEMPLE POND LAY STILL.
A6 AN OMEN:
A6 HEAVEN SENDS A SIGN:
A6 IT IS INAUSPICIOUS:
B6 THE LANTERNS GUTTERED AT ONCE.
B6 A CRANE FLEW BACKWARDS.
B6 THE TEA LEAVES FORMED A BROKEN GATE.
F7 A STAR WENT OUT AS I WATCHED.
F7 THE OLDEST OAK DROPPED A BRANCH WITHOUT WIND.
F7 THE NIGHTINGALE SANG AT NOON.
A7 THE STARS WARN:
A7 A SIGN IN THE BOUGHS:
A7 THE LEAVES SAY:
B7 THE MOON ROSE RED.
B7 THE BLOSSOMS CLOSED AT DAWN.
B7 THE DEER WOULD NOT LOOK AT ME.
)VOICE";

const char* const kCurse = R"VOICE(
= curse
F0 MAY IT ROT, AND WHOEVER'S BEHIND IT.
F0 LET THEM CHOKE ON IT.
F0 BAD LUCK FOLLOW IT HOME.
A0 CURSE IT.
A0 DAMN IT ALL.
A0 LET {GIVER.GOD} SEE IT.
B0 MAY IT ALL COME BACK DOUBLE.
B0 LET EVERY DOOR SHUT ON THEM.
B0 MAY THEIR BREAD TURN TO ASH.
F1 MAY THE SEA TAKE THEM, AND KEEP THEM.
F1 LET THE FROST FIND THEIR BEDS.
F1 NO CAIRN FOR THEM, AND NO SONG.
A1 HEAR ME, {GIVER.GOD}.
A1 SPIT ON IT.
A1 LET IT BE SAID:
B1 MAY THEIR HALL BURN.
B1 NO SKALD WILL SING THEIR NAME.
B1 MAY WOLVES WALK THEIR FIELDS.
F2 MAY THEIR FIELDS GROW NOTHING BUT NETTLES.
F2 BLIGHT ON THEM, AND ON THEIR SEED.
F2 LET THEIR KETTLE NEVER BOIL.
A2 CURSE THEM.
A2 {GIVER.GOD} FORGIVE ME:
A2 I'LL SAY IT:
B2 MAY THEIR MILK SOUR.
B2 MAY THEIR ROOF LEAK ON THEIR BED.
B2 LET THE RATS HAVE THEIR GRAIN.
F3 MAY THEIR WELLS RUN SALT.
F3 MAY THEIR SHADOW SHRINK TO NOTHING AT NOON.
F3 LET THE SAND COVER THEIR NAME.
A3 BY THE SUN'S EYE,
A3 LET {GIVER.GOD} HEAR THIS:
A3 O SUN, SEE THIS:
B3 MAY NO GUEST EVER CROSS THEIR DOOR.
B3 MAY THEIR CARAVAN LOSE THE STARS.
B3 LET THE SCORPION FIND THEIR SANDALS.
F4 MAY THEIR HORSE STUMBLE ON THE LAST HILL.
F4 LET THE WOLVES HAVE THEIR HERD.
F4 NO GRASS FOR THEM. NOT EVER.
A4 SPIT.
A4 HEAR IT, SKY.
A4 LET IT BE:
B4 MAY THEIR FIRE GO OUT IN WINTER.
B4 MAY THEIR ARROWS FALL SHORT.
B4 LET THE WIND FORGET THEM.
F5 MAY THE MUD TAKE THEM TO THE KNEES, THEN THE NECK.
F5 LET THE RIVER SPIT THEM OUT.
F5 MAY THEIR BOAT FIND EVERY ROCK.
A5 MUD AND ROT ON IT.
A5 THE RIVER HEAR ME:
A5 SPIT IN THE WATER.
B5 MAY THEIR NETS COME UP EMPTY.
B5 LET THE FOG LEAD THEM ROUND IN CIRCLES.
B5 MAY THE EELS EAT WELL.
F6 MAY THEIR ANCESTORS TURN THEIR FACES AWAY.
F6 LET THEIR NAME BE STRUCK FROM EVERY TABLET.
F6 MAY NO ONE SWEEP THEIR GRAVES.
A6 HEAVEN WITNESS THIS:
A6 FORGIVE MY TONGUE, BUT
A6 I SAY IT PLAINLY:
B6 MAY THEY LOSE ALL FACE.
B6 MAY THEIR LINE END WITH THEM.
B6 LET THE MAGISTRATES FORGET THEIR NAME.
F7 MAY NO TREE EVER SHADE THEM.
F7 LET THE STARS LOOK AWAY.
F7 MAY THEIR SONG END MID-WORD.
A7 HEAR ME, OLD TREES.
A7 UNDER COLD STARS,
A7 LET IT BE SUNG:
B7 MAY THE ROOTS TRIP THEM.
B7 MAY THE MOON NEVER FIND THEM.
B7 LET THE LEAVES FORGET THEIR STEP.
)VOICE";

const char* const kThreat = R"VOICE(
= threat
F0 WALK AWAY WHILE YOU STILL CAN.
F0 ONE MORE STEP AND YOU'LL REGRET IT.
F0 I'VE BURIED BETTER THAN YOU.
A0 CAREFUL.
A0 LISTEN WELL.
A0 I'LL SAY THIS ONCE.
F1 MY AXE HAS A NAME. YOU'LL LEARN IT.
F1 THE SEA IS DEEP AND NOBODY COUNTS WHAT IT EATS.
F1 ONE MORE WORD AND THE RAVENS EAT.
A1 HEAR THIS.
A1 MARK ME, STRANGER.
A1 STEP BACK.
F2 I'VE A PITCHFORK AND A BAD TEMPER. TRY ME.
F2 THERE'S A DEEP MILLPOND HERE. NOBODY DRAINS IT.
F2 GO NOW, OR GO IN A CART.
A2 NOW SEE HERE.
A2 MARK MY WORDS.
A2 THAT'S ENOUGH.
F3 THE DESERT HAS ROOM FOR ONE MORE NAMELESS GRAVE.
F3 YOU ARE NO LONGER MY GUEST. THINK ON THAT.
F3 THE SAND DRINKS BLOOD AND ASKS NO QUESTIONS.
A3 BEWARE, STRANGER.
A3 HEAR ME WELL.
A3 GUEST NO LONGER,
F4 THE STEPPE IS WIDE. NOBODY WILL FIND YOU.
F4 MY BOW IS STRUNG. LEAVE.
F4 ONE ARROW. THAT IS ALL IT TAKES.
A4 GO.
A4 BACK.
A4 HEAR ME.
F5 THE MARSH SWALLOWS THINGS. NOBODY ASKS AFTER THEM.
F5 THE EELS ARE ALWAYS HUNGRY.
F5 PUSH ME AND YOU'LL SWIM HOME. FACE DOWN.
A5 CAREFUL, NOW.
A5 LISTEN, DRY-FOOT.
A5 STEP SOFT.
F6 YOU PRESUME TOO MUCH. IT WILL COST YOU.
F6 THIS ONE IS PATIENT. THIS ONE IS NOT FORGIVING.
F6 LEAVE NOW, AND SPARE US BOTH THE SHAME.
A6 TAKE CARE.
A6 WITH RESPECT, NO MORE.
A6 BE WARNED.
F7 THE ROOTS HAVE HELD BETTER THAN YOU, BENEATH THEM.
F7 THE WOOD IS OLD AND IT DOES NOT FORGIVE.
F7 THE STARS WILL NOT SEE WHERE YOU FALL.
A7 GO, WHILE THE LEAVES ALLOW IT.
A7 BEWARE.
A7 HEAR THE WOOD.
Mfear I'LL DO WHAT I MUST. DON'T MAKE ME.
Mfear DON'T COME CLOSER. I MEAN IT.
Mfear I'M FRIGHTENED. THAT MAKES ME DANGEROUS.
Mgreed THIS IS MINE. TOUCH IT AND BLEED.
Mgreed IT'S NOT WORTH YOUR LIFE. IT'S WORTH MINE.
Mgreed I DON'T SHARE. I NEVER HAVE.
Mgrief I'VE NOTHING LEFT TO LOSE. REMEMBER THAT.
Mgrief I'VE DUG ENOUGH GRAVES. ONE MORE IS EASY.
Mgrief DON'T TEST SOMEONE WITH NOTHING LEFT.
Mpride NOBODY SPEAKS TO ME LIKE THAT.
Mpride YOU DON'T KNOW WHO YOU'RE TALKING TO.
Mpride I'LL MAKE AN EXAMPLE OF YOU.
Mdevotion {GIVER.GOD} WILL FORGIVE ME FOR THIS.
Mdevotion I'LL DEFEND THE FAITH WITH MY HANDS.
Mdevotion THE GODS ARE ON MY SIDE, NOT YOURS.
Mlove TOUCH WHAT I LOVE AND I'LL KILL YOU.
Mlove FOR MY OWN I'D DO ANYTHING. ANYTHING.
Mlove STAY AWAY FROM WHAT'S MINE.
Mduty I'M SWORN TO STOP YOU. I WILL.
Mduty I HAVE MY ORDERS. DON'T TEST THEM.
Mduty NOBODY PASSES. NOT YOU, NOT ANYONE.
Mvengeance I'VE WAITED YEARS. I CAN WAIT FOR YOU.
Mvengeance I KNOW YOUR FACE NOW. I WON'T FORGET.
Mvengeance BLOOD WANTS BLOOD. YOURS WILL DO.
Mshame SAY IT TO ANYONE AND YOU'RE DEAD.
Mshame NOBODY CAN KNOW. NOBODY.
Mshame I'LL NOT BE SHAMED AGAIN. NOT BY YOU.
Mhope DON'T TAKE THIS FROM ME. I WON'T LET YOU.
Mhope I'VE COME TOO FAR TO BE STOPPED NOW.
Mhope THIS IS MY LAST CHANCE. STAND ASIDE.
)VOICE";

const char* const kInsult = R"VOICE(
= insult
F0 YOU'RE A FOOL, AND A SLOW ONE.
F0 GO HOME TO YOUR MOTHER.
F0 I'VE SEEN BRAVER SHEEP.
A0 HAH.
A0 LOOK AT YOU.
A0 LISTEN, YOU.
B0 YOU COULDN'T FIND WATER IN A WELL.
B0 YOU'VE THE WIT OF A BOOT.
B0 EVEN THE DOGS LAUGH AT YOU.
F1 YOU FIGHT LIKE A WET SAIL FLAPS.
F1 MILK-BEARD. GO BACK TO YOUR MOTHER'S HEARTH.
F1 THE SKALDS WOULD NOT WASTE A RHYME ON YOU.
A1 HAH!
A1 SO.
A1 LOOK AT THIS ONE.
B1 A HALF-THAWED FISH HAS MORE SPINE.
B1 YOUR SHIELD IS FOR HIDING.
B1 EVEN THE GULLS PITY YOU.
F2 YOU'RE ALL CHAFF AND NO GRAIN.
F2 I'VE SEEN TURNIPS WITH MORE SENSE.
F2 GO AND MUCK OUT SOMETHING. IT'S ALL YOU'RE FIT FOR.
A2 WELL, LOOK AT YOU.
A2 HONESTLY.
A2 OH, PLEASE.
B2 ALL BARK AND NO BREAD.
B2 YOUR MOTHER SHOULD HAVE KEPT GEESE.
B2 YOU COULDN'T PLOUGH A STRAIGHT FURROW.
F3 YOU WOULD SELL WATER TO THE DROWNING.
F3 A GOAT HAS BETTER MANNERS AT TABLE.
F3 YOUR FATHER'S WELL WAS DRY, I THINK.
A3 O FOOL,
A3 SEE THIS ONE.
A3 PITIFUL.
B3 YOUR SHADOW IS ASHAMED TO FOLLOW YOU.
B3 THE SAND FLEAS HAVE MORE HONOUR.
B3 YOU ARE A GUEST NOBODY INVITED.
F4 YOU RIDE LIKE A SACK OF MEAL.
F4 A FOAL HAS MORE SENSE THAN YOU.
F4 WALKER. NO HORSE WOULD CARRY YOU.
A4 HAH! YOU.
A4 LOOK.
A4 YOU.
B4 EVEN THE CROWS IGNORE YOU.
B4 YOUR BOW IS FOR SHOW.
B4 GO BACK TO YOUR WALLS.
F5 YOU'VE THE WIT OF A DROWNED FROG.
F5 YOU COULDN'T POLE A BOAT ACROSS A BUCKET.
F5 YOU'RE ALL FOG AND NO SHORE.
A5 WELL, NOW.
A5 HARK AT IT.
A5 OH, YOU.
B5 THE LEECHES WOULDN'T HAVE YOU.
B5 YOU'D SINK IN A PUDDLE.
B5 EVEN THE MUD'S EMBARRASSED.
F6 YOU HAVE NO MANNERS AND NO ANCESTORS, IT SEEMS.
F6 YOUR FAMILY MUST BE VERY PATIENT.
F6 SUCH CRUDENESS. ONE IS ASTONISHED.
A6 HOW UNFORTUNATE.
A6 FORGIVE MY FRANKNESS:
A6 ONE CANNOT HELP SAYING IT:
B6 YOU SHAME YOUR FATHERS.
B6 YOUR BRUSHWORK MUST BE DREADFUL.
B6 A RICE-SACK HAS MORE GRACE.
F7 YOU STAMP THROUGH LIFE LIKE A BOAR IN BLUEBELLS.
F7 YOU ARE A WEED THAT THINKS IT IS A FLOWER.
F7 EVEN THE MAYFLIES FIND YOU DULL.
A7 ALAS.
A7 POOR THING.
A7 LISTEN, SAPLING.
B7 THE STARS DO NOT KNOW YOUR NAME.
B7 YOUR SONG IS ALL ONE NOTE.
B7 THE TREES ARE EMBARRASSED FOR YOU.
)VOICE";

const char* const kGrief = R"VOICE(
= grief
F0 THE HOUSE IS TOO QUIET NOW.
F0 SOME DAYS I FORGET, AND THEN I REMEMBER.
F0 I KEEP TURNING TO SAY SOMETHING. NOBODY'S THERE.
A0 I'M SORRY.
A0 FORGIVE ME.
A0 IT'S JUST...
F1 THE SEA HAS TAKEN ITS SHARE. IT ALWAYS DOES.
F1 I RAISED A CAIRN. IT DID NOT HELP.
F1 THE MEAD TASTES OF ASHES NOW.
A1 SO IT GOES.
A1 AYE.
A1 THE GODS ARE COLD.
F2 I STILL SET A PLACE AT THE TABLE.
F2 THE GARDEN'S GONE TO WEEDS. I CAN'T FACE IT.
F2 THE CHAIR BY THE FIRE IS EMPTY.
A2 I'M SORRY, IT'S...
A2 PAY ME NO MIND.
A2 OH, GODS.
F3 THE TENT IS TOO WIDE FOR ONE.
F3 I POUR TWO CUPS. ONE GOES COLD.
F3 THE STARS ARE THE SAME. NOTHING ELSE IS.
A3 ALAS.
A3 FORGIVE MY TEARS.
A3 O SORROW.
F4 THE SADDLE HANGS EMPTY ON THE POLE.
F4 THE WIND BLOWS THROUGH THE TENT NOW.
F4 I SING THE SONG FOR THE DEAD. NOBODY ANSWERS.
A4 HM.
A4 SO.
A4 THE SKY TAKES.
F5 THE RIVER TOOK IT ALL DOWN, AND DIDN'T BRING IT BACK.
F5 THE BOAT'S STILL TIED UP. I CAN'T TAKE IT OUT.
F5 THE FOG'S IN MY CHEST AND WON'T LIFT.
A5 AH.
A5 WELL.
A5 SORRY. IT'S THE DAMP.
F6 I BURN INCENSE AT THE SHRINE EACH NIGHT. IT IS NOT ENOUGH.
F6 THE TABLET HAS A NEW NAME. I CANNOT READ IT ALOUD.
F6 FORGIVE ME. I HAVE LOST MY COMPOSURE.
A6 FORGIVE THIS UNSEEMLINESS.
A6 ALAS, ALAS.
A6 THIS ONE IS SORRY.
F7 A TREE FELL IN THE NIGHT, AND THE WOOD IS LOUDER FOR IT.
F7 THERE IS A STAR I CANNOT FIND ANY MORE.
F7 I SING THE SONG, BUT IT HAS A HOLE IN IT.
A7 LISTEN TO THE WOOD.
A7 THE LEAVES FALL.
A7 FORGIVE MY RAIN.
Mfear AND I'M FRIGHTENED IT'S NOT OVER.
Mfear I KEEP WAITING FOR THE NEXT BLOW.
Mfear WHAT IF I'M NEXT?
Mgreed AND THE DEBTS DIDN'T DIE WITH THEM.
Mgreed ALL I SAVED, AND NONE OF IT HELPED.
Mgreed I'D GIVE EVERY COIN TO UNDO IT.
Mgrief I DON'T KNOW HOW TO STOP.
Mgrief IT DOESN'T GET SMALLER. I GET BIGGER.
Mgrief I MISS WHAT'S GONE IN EVERY ROOM.
Mpride I WON'T WEEP IN FRONT OF THEM.
Mpride I HOLD MY HEAD UP. IT'S ALL I HAVE.
Mpride THEY'LL NOT SEE ME BREAK.
Mdevotion I PRAY, AND THE SILENCE PRAYS BACK.
Mdevotion {GIVER.GOD} KEEPS THE LOST. I TELL MYSELF.
Mdevotion THE PRIESTS SAY IT'S A BLESSING. IT ISN'T.
Mlove I NEVER SAID IT ENOUGH.
Mlove I'D TRADE MY YEARS FOR ONE MORE DAY.
Mlove I STILL REACH OUT IN THE NIGHT.
Mduty I HAVE WORK TO DO. I'LL GRIEVE AFTER.
Mduty I'LL DO WHAT HAS TO BE DONE.
Mduty SOMEONE HAS TO KEEP THINGS GOING.
Mvengeance I'LL MOURN WHEN IT'S ANSWERED.
Mvengeance TEARS LATER. FIRST, A RECKONING.
Mvengeance SOMEONE OWES ME FOR THIS.
Mshame I WASN'T THERE WHEN IT MATTERED.
Mshame I SHOULD HAVE SAID SOMETHING. I DIDN'T.
Mshame IT WAS MY FAULT. I KNOW IT.
Mhope BUT THE SPRING STILL COMES. I'VE SEEN IT.
Mhope NOTHING IS LOST FOREVER. I BELIEVE THAT.
Mhope SOMETHING GOOD MUST COME OF IT.
)VOICE";

const char* const kDoubt = R"VOICE(
= doubt
F0 OR SO THEY SAY.
F0 I'VE ONLY THEIR WORD FOR IT.
F0 I WANT TO BELIEVE IT. I DON'T.
A0 HM.
A0 MAYBE.
A0 I WONDER.
B0 SOMETHING DOESN'T SIT RIGHT.
B0 IT'S TOO NEAT A STORY.
B0 PEOPLE SAY ALL SORTS.
F1 A SMOOTH TONGUE HIDES A SHARP KNIFE.
F1 I WILL BELIEVE IT WHEN THE ICE MELTS.
F1 THE SKALDS SAY MANY THINGS. FEW ARE TRUE.
A1 SO THE SKALDS SAY.
A1 AYE, PERHAPS.
A1 COLD WORDS.
B1 I HAVE SEEN CALM SEAS DROWN SHIPS.
B1 WORDS ARE CHEAP; DEEDS COST.
B1 THE TALE HAS A HOLE IN IT.
F2 THAT'S A TALE FOR THE ALEHOUSE.
F2 PULL THE OTHER ONE.
F2 I'LL BELIEVE IT WHEN I SEE IT.
A2 WELL...
A2 HMM.
A2 I DON'T KNOW.
B2 IT SMELLS LIKE A BAD EGG.
B2 SOMEONE'S TELLING IT CROOKED.
B2 THERE'S MORE TO IT, MARK ME.
F3 THE MIRAGE ALSO LOOKS LIKE WATER.
F3 SWEET WORDS, BUT I TASTE SAND IN THEM.
F3 A MERCHANT'S PROMISE AND A DESERT WIND.
A3 PERHAPS, O GUEST.
A3 SO IT IS SAID.
A3 AH, BUT...
B3 THE TRACKS SAY OTHERWISE.
B3 I HAVE SEEN MANY MIRAGES.
B3 A STORY IS NOT A WELL.
F4 MAYBE. THE WIND SAYS MANY THINGS.
F4 I DID NOT SEE IT. SO.
F4 SMOKE, NOT FIRE.
A4 WIND-TALK.
A4 MAYBE, RIDER.
A4 SO?
B4 I TRUST TRACKS, NOT TALES.
B4 WORDS ARE WIND.
B4 THE GRASS HIDES A LOT.
F5 THE FOG MAKES EVERY POST LOOK LIKE A MAN.
F5 MUDDY WATER, MUDDY TALE.
F5 I'VE HEARD THAT ONE BEFORE, DOWNSTREAM.
A5 HMPH.
A5 MAYBE SO.
A5 FOG-TALK.
B5 SOMETHING'S UNDER THE SURFACE.
B5 THE STORY'S GOT A LEAK.
B5 I'D NOT STAND ON THAT PLANK.
F6 FORGIVE ME, BUT THE ACCOUNT IS INCOMPLETE.
F6 ONE WISHES TO BELIEVE. ONE CANNOT, QUITE.
F6 THE RECORDS SAY OTHERWISE, I THINK.
A6 WITH RESPECT,
A6 ONE IS UNCERTAIN.
A6 ONE WONDERS.
B6 THE BRUSH STROKES DO NOT MATCH.
B6 SOMETHING IS LEFT UNSAID.
B6 THE COURTESIES ARE TOO PERFECT.
F7 THE MOON IS NOT AS IT SEEMS. NOR IS THIS.
F7 A SWEET SONG CAN HIDE A SOUR NOTE.
F7 THE TREES ARE QUIET. THEY DO NOT BELIEVE IT EITHER.
A7 PERHAPS, PERHAPS.
A7 THE MOON IS TWO-FACED.
A7 THE LEAVES WHISPER:
B7 SOMETHING HAS NOT BEEN SAID.
B7 THE STARS SAY OTHERWISE.
B7 THERE IS A SHADOW IN IT.
)VOICE";

const char* const kWarning = R"VOICE(
= warning
F0 MIND THE ROAD AFTER DARK.
F0 DON'T TRUST WHAT YOU SEE THERE.
F0 THEY'LL BE WATCHING FOR YOU.
A0 CAREFUL.
A0 MIND YOURSELF.
A0 A WORD OF ADVICE:
F1 THE ICE IS THINNEST WHERE IT LOOKS STRONGEST.
F1 KEEP YOUR BACK TO A WALL AND YOUR AXE TO HAND.
F1 WHERE THE RAVENS CIRCLE, DO NOT LINGER.
A1 HEED ME.
A1 WATCH YOURSELF.
A1 MARK THIS:
F2 DON'T EAT ANYTHING YOU DIDN'T SEE COOKED.
F2 KEEP TO THE ROAD. THE FIELDS HAVE TEETH.
F2 LOCK YOUR DOOR, AND THEN CHECK IT.
A2 MIND YOU,
A2 BE CAREFUL, NOW.
A2 ONE THING:
F3 NEVER FOLLOW A FIRE YOU CANNOT REACH.
F3 CARRY MORE WATER THAN YOU THINK.
F3 BEWARE THE SMILING HOST WITH NO BREAD.
A3 BEWARE.
A3 HEED ME, GUEST.
A3 BY THE SUN,
F4 WATCH THE HORIZON. ALWAYS.
F4 DON'T SLEEP WITHOUT A FIRE.
F4 TRUST YOUR HORSE'S EARS.
A4 WATCH.
A4 CAREFUL, RIDER.
A4 HEAR.
F5 DON'T STEP WHERE THE REEDS GO QUIET.
F5 THE FOG LIES. FOLLOW THE BANK.
F5 NEVER DRINK STANDING WATER.
A5 MIND THE MUD.
A5 CAREFUL, NOW.
A5 LISTEN:
F6 BE CAREFUL WHOM YOU BOW TO.
F6 WALLS HAVE EARS, AND EARS HAVE MASTERS.
F6 A SMILING OFFICIAL IS THE MOST DANGEROUS KIND.
A6 PLEASE TAKE CARE.
A6 WITH RESPECT,
A6 A HUMBLE WARNING:
F7 DO NOT STRAY FROM THE PATH WHEN THE MOON IS NEW.
F7 THE OLD WOOD DOES NOT LOVE FIRE. NOR STRANGERS.
F7 IF THE BIRDS FALL SILENT, RUN.
A7 BEWARE, WANDERER.
A7 GENTLY:
A7 HEED THE LEAVES.
Mfear SOMETHING'S OUT THERE. I'VE FELT IT.
Mfear I'VE HEARD THINGS AT NIGHT. BAD THINGS.
Mfear DON'T GO ALONE IF YOU CAN HELP IT.
Mgreed EVERYONE THERE WANTS A PIECE.
Mgreed COUNT YOUR COIN TWICE THERE.
Mgreed SOMEONE WILL TRY TO CHEAT YOU.
Mgrief IT'S TAKEN ENOUGH ALREADY.
Mgrief DON'T LET IT TAKE YOU TOO.
Mgrief I'VE LOST ENOUGH. DON'T BE NEXT.
Mpride THE PROUD DON'T COME BACK FROM THERE.
Mpride DON'T THINK YOU'RE TOO GOOD TO FALL.
Mpride BETTER FOLK THAN YOU HAVE TRIED.
Mdevotion {GIVER.GOD} DOESN'T WALK THERE.
Mdevotion TAKE A PRAYER WITH YOU. TAKE TWO.
Mdevotion KEEP YOUR FAITH CLOSE OUT THERE.
Mlove COME BACK. THAT'S ALL I ASK.
Mlove DON'T BE A HERO. BE ALIVE.
Mlove I CAN'T LOSE YOU TOO.
Mduty STAY ON THE ROAD. THAT'S AN ORDER.
Mduty REPORT WHAT YOU SEE. TOUCH NOTHING.
Mduty THERE ARE RULES OUT THERE. KEEP THEM.
Mvengeance THEY'LL KNOW YOU'RE COMING.
Mvengeance THEY DON'T FIGHT FAIR. NEITHER SHOULD YOU.
Mvengeance WATCH FOR A KNIFE IN THE BACK.
Mshame DON'T MAKE MY MISTAKES.
Mshame DON'T DO WHAT I DID.
Mshame SOME THINGS I WON'T SPEAK OF. GO CAREFUL.
Mhope COME BACK, AND IT'LL ALL BE WORTH IT.
Mhope BE CAREFUL. WE NEED YOU.
Mhope GO CAREFUL. THERE'S STILL A CHANCE.
)VOICE";

const char* const kBoast = R"VOICE(
= boast
F0 NOBODY DOES IT BETTER.
F0 I'VE DONE HARDER THINGS BEFORE BREAKFAST.
F0 THEY STILL TALK ABOUT ME IN {HOME}.
A0 HAH.
A0 WELL,
A0 I'LL TELL YOU:
F1 I HAVE ROWED THROUGH STORMS THAT ATE WHOLE FLEETS.
F1 THE SKALDS HAVE THREE SONGS ABOUT ME. FOUR, SOON.
F1 MY AXE HAS TASTED BETTER THAN YOU'LL MEET.
A1 HAH!
A1 ASK THE SKALDS.
A1 I SAY THIS:
F2 BEST HANDS IN {HOME}. ASK ANYONE.
F2 I'VE WON THE FAIR THREE YEARS RUNNING.
F2 MY BREAD'S KNOWN TWO VILLAGES OVER.
A2 NOT TO BRAG, BUT
A2 WELL, NOW.
A2 I'LL HAVE YOU KNOW:
F3 MY FATHERS CROSSED THE GREAT SAND WITHOUT A MAP.
F3 THE STARS THEMSELVES ENVY MY EYES.
F3 NONE IN {HOME} CAN MATCH MY HOSPITALITY. NONE.
A3 BEHOLD.
A3 IT IS KNOWN:
A3 BY THE SUN,
F4 I HAVE RIDDEN FROM SUNRISE TO SUNSET AND BACK.
F4 MY ARROW FINDS THE EYE OF A HAWK.
F4 THE HERDS KNOW MY VOICE.
A4 LOOK.
A4 SEE.
A4 KNOW IT, STRANGER:
F5 I CAN POLE THE WHOLE MARSH BLINDFOLD.
F5 BIGGEST EEL ON THE RIVER. THEY STILL TALK OF IT.
F5 I KNOW EVERY CHANNEL. EVERY ONE.
A5 HA! ON THE WATER,
A5 WELL, NOW,
A5 ASK ANY FERRYMAN:
F6 MY FAMILY HAS SERVED SEVEN GENERATIONS WITH HONOUR.
F6 MY BRUSHWORK HAS BEEN PRAISED AT COURT.
F6 FORGIVE ME, BUT FEW COULD HAVE DONE IT.
A6 IF I MAY SAY,
A6 IT IS SAID:
A6 WITHOUT FALSE MODESTY,
F7 I HAVE SEEN A HUNDRED SPRINGS. I WAS NOT IDLE.
F7 MY SONGS ARE SUNG IN WOODS I NEVER WALKED.
F7 THE STARS TAUGHT ME. I LEARNED WELL.
A7 AH,
A7 LISTEN, SAPLING:
A7 IT IS SUNG:
Mfear I'M NOT AFRAID. NOT OF THIS.
Mfear FEAR? I'VE FORGOTTEN THE WORD.
Mfear I'VE FACED WORSE. I THINK.
Mgreed I COULD BUY THIS STREET TWICE OVER.
Mgreed EVERY DEAL I MAKE COMES OUT AHEAD.
Mgreed MY PURSE IS HEAVIER THAN MOST.
Mgrief I'VE SURVIVED EVERYTHING. EVEN THIS.
Mgrief I'VE OUTLIVED ALL MY RIVALS.
Mgrief NOTHING BREAKS ME. NOTHING.
Mpride THERE'S NONE BETTER. NONE.
Mpride THEY'LL SING OF ME WHEN I'M GONE.
Mpride I'VE NEVER LOST. NOT ONCE.
Mdevotion {GIVER.GOD} FAVOURS ME. IT'S PLAIN.
Mdevotion I'VE NEVER MISSED A PRAYER.
Mdevotion THE GODS WALK BESIDE ME.
Mlove I'D WALK THROUGH FIRE FOR MINE.
Mlove NOBODY HAS TRUER FRIENDS THAN I DO.
Mlove MY FAMILY IS THE PROUDEST IN {HOME}.
Mduty I'VE NEVER MISSED A WATCH.
Mduty NOBODY SERVES LONGER OR BETTER.
Mduty TWENTY YEARS AND NOT ONE LAPSE.
Mvengeance NOBODY WRONGS ME TWICE.
Mvengeance EVERY SCORE I'VE HAD, I'VE SETTLED.
Mvengeance MY ENEMIES ARE ALL IN THE GROUND.
Mshame I'M STILL THE BEST AT IT. STILL.
Mshame WHATEVER THEY SAY, I'M GOOD AT THIS.
Mshame I WAS SOMEBODY ONCE.
Mhope I'LL BE THE GREATEST YET. YOU'LL SEE.
Mhope MY BEST DAYS ARE AHEAD.
Mhope ONE DAY THEY'LL KNOW MY NAME.
)VOICE";

const char* const kRefusal = R"VOICE(
= refusal
F0 NO. NOT FOR ANY PRICE.
F0 ASK ME AGAIN AND THE ANSWER'S THE SAME.
F0 I CAN'T. DON'T MAKE ME SAY WHY.
A0 NO.
A0 I'M SORRY. NO.
A0 NOT A CHANCE.
F1 NO. AND A NO SPOKEN IS A STONE THROWN.
F1 THE SEA WILL FREEZE FIRST.
F1 NOT FOR ALL THE SILVER UNDER THE SEA.
A1 NO. AND AGAIN, NO.
A1 NEVER.
A1 I SAY NO.
F2 NO, AND THAT'S MY LAST WORD ON IT.
F2 NOT IF YOU OFFERED ME THE MILL ITSELF.
F2 WHEN PIGS PLOUGH. NOT BEFORE.
A2 NO, LOVE.
A2 I'M AFRAID NOT.
A2 NOT ON YOUR LIFE.
F3 THIS I CANNOT GIVE, NOT EVEN TO A GUEST.
F3 NO, THOUGH IT BREAKS THE LAW OF THE TENT.
F3 NOT FOR ALL THE WATER IN THE WELLS.
A3 FORGIVE ME, NO.
A3 IT CANNOT BE.
A3 NO, O GUEST.
F4 NO. THAT IS ALL.
F4 NO. THE WIND DOES NOT TURN FOR ME.
F4 ASK THE SKY. IT WILL SAY NO TOO.
A4 NO. DONE.
A4 NOT EVER.
A4 NO MORE.
F5 NO. NOT IF THE RIVER RAN BACKWARDS.
F5 THAT'S A NO, AND IT'S NOT SINKING.
F5 ASK THE EELS. THEY'LL SAY YES. I SAY NO.
A5 NO, AND NO.
A5 NOT LIKELY.
A5 AH, NO.
F6 WITH THE DEEPEST REGRET, THIS ONE MUST DECLINE.
F6 IT WOULD BE IMPROPER. I CANNOT.
F6 MY ANCESTORS WOULD NOT PERMIT IT.
A6 FORGIVE ME, BUT NO.
A6 REGRETTABLY, NO.
A6 I MUST DECLINE.
F7 NO, AS THE OAK SAYS NO TO THE AXE.
F7 THE STARS WILL NOT MOVE, AND NOR WILL I.
F7 NOT THIS SPRING. NOT ANY SPRING.
A7 NO, LITTLE ONE.
A7 GENTLY, NO.
A7 THE ROOTS SAY NO.
Mfear I'M TOO FRIGHTENED. I'M SORRY.
Mfear I CAN'T GO BACK THERE. I CAN'T.
Mfear IT'S TOO DANGEROUS. FOR ALL OF US.
Mgreed THE PRICE ISN'T WORTH IT.
Mgreed NOT UNLESS THERE'S MORE IN IT FOR ME.
Mgreed I DON'T WORK FOR NOTHING.
Mgrief I'VE NOTHING LEFT TO GIVE.
Mgrief I CAN'T. NOT AFTER EVERYTHING.
Mgrief LET ME BE. PLEASE.
Mpride I'LL NOT LOWER MYSELF TO THAT.
Mpride WHO DO YOU THINK I AM?
Mpride I'VE MORE PRIDE THAN THAT.
Mdevotion {GIVER.GOD} FORBIDS IT.
Mdevotion IT'S AGAINST EVERYTHING I BELIEVE.
Mdevotion THE GODS WOULD TURN FROM ME.
Mlove I CAN'T LEAVE MY OWN. I WON'T.
Mlove IT WOULD HURT THE ONES I LOVE.
Mlove NOT IF IT PUTS MY OWN AT RISK.
Mduty I'M SWORN TO OTHERWISE.
Mduty IT'S NOT MINE TO GIVE.
Mduty MY ORDERS SAY NO. SO DO I.
Mvengeance NOT TILL THE DEBT IS PAID.
Mvengeance I'LL NOT FORGIVE. NOT YET.
Mvengeance AFTER WHAT WAS DONE? NO.
Mshame I CAN'T FACE THEM. DON'T ASK ME.
Mshame I'VE DONE ENOUGH DAMAGE.
Mshame NOT AFTER WHAT I DID.
Mhope NOT YET. THERE MAY BE ANOTHER WAY.
Mhope WAIT. LET'S NOT GIVE UP YET.
Mhope NO. IT CAN STILL BE SAVED.
)VOICE";

const char* const kSurprise = R"VOICE(
= surprise
F0 WELL. I DIDN'T EXPECT THAT.
F0 YOU? HERE?
F0 NOW THAT'S A THING.
A0 WHAT?
A0 WELL, NOW.
A0 GOODNESS.
B0 I'D NOT HAVE GUESSED IT.
B0 THAT'S A TURN.
B0 I NEVER SAW THAT COMING.
F1 BY THE ICE! I DID NOT SEE THAT COMING.
F1 THE SEA SPITS UP STRANGE THINGS.
F1 HAH! THE GODS ARE JESTERS TODAY.
A1 HAH!
A1 BY {GIVER.GOD}!
A1 WHAT?
B1 THE SKALDS WILL LOVE THIS.
B1 THE WORLD STILL HAS TEETH.
B1 I'LL DRINK TO THAT, OR AGAINST IT.
F2 WELL I NEVER.
F2 BLESS ME, I'D NEVER HAVE THOUGHT IT.
F2 YOU COULD KNOCK ME DOWN WITH A FEATHER.
A2 OH!
A2 GOODNESS ME.
A2 WELL!
B2 WAIT TILL THE MARKET HEARS.
B2 I MUST SIT DOWN.
B2 WHO'D HAVE THOUGHT?
F3 BY THE SUN'S EYE! WHAT WONDER IS THIS?
F3 THE STARS HAVE PLAYED A TRICK ON ME.
F3 TRULY, THE DESERT HIDES MARVELS.
A3 O WONDER!
A3 BY THE SUN!
A3 AH!
B3 I MUST TELL THE CARAVANS.
B3 NEVER IN ALL MY YEARS.
B3 IT IS LIKE A TALE.
F4 HAH! THE SKY SURPRISES ME.
F4 I DID NOT SEE THAT. AND I SEE FAR.
F4 SO. A NEW THING.
A4 HAH!
A4 OH?
A4 SKY!
B4 THE HERDERS WILL LAUGH.
B4 THE WIND CHANGED.
B4 STRANGE DAY.
F5 WELL, DROWN ME.
F5 THE RIVER'S FULL OF SURPRISES TODAY.
F5 I'LL BE A HERON'S BREAKFAST.
A5 OH!
A5 WELL!
A5 HARK!
B5 NEVER SAW THE LIKE.
B5 THAT CAME OUT OF THE FOG.
B5 WAIT TILL THE FERRYMEN HEAR.
F6 HOW REMARKABLE. ONE IS QUITE ASTONISHED.
F6 THIS IS MOST UNEXPECTED.
F6 THE ANCESTORS DID NOT FORESEE THIS.
A6 AH!
A6 EXTRAORDINARY.
A6 FORGIVE MY SURPRISE.
B6 THIS IS MOST IRREGULAR.
B6 ONE MUST RECORD THIS.
B6 I AM LOST FOR WORDS.
F7 OH! A STAR FALLS IN DAYLIGHT.
F7 THE OLD TREES NEVER TOLD ME THIS.
F7 HOW STRANGE AND HOW BEAUTIFUL.
A7 OH!
A7 AH, WONDER.
A7 LOOK!
B7 THE LEAVES WILL WHISPER OF IT.
B7 A NEW SONG BEGINS.
B7 THE STARS ARE LAUGHING.
)VOICE";

}  // namespace

void wisdomBlocks(std::vector<const char*>& out) {
  out.push_back(kProverb);
  out.push_back(kSaying);
  out.push_back(kOmen);
  out.push_back(kCurse);
  out.push_back(kThreat);
  out.push_back(kInsult);
  out.push_back(kGrief);
  out.push_back(kDoubt);
  out.push_back(kWarning);
  out.push_back(kBoast);
  out.push_back(kRefusal);
  out.push_back(kSurprise);
}

}  // namespace voicedata
}  // namespace saga
}  // namespace story
