// M6b "Sagas": the voice's social keys (greet welcome plea urgency thanks farewell blessing oath vow praise comfort
// apology relief). VOICE lane. The block format and the rules: voice.cpp. One raw literal per key (MSVC's 16 KB cap).
//
// The eight idioms: 0 plain (short, practical, no imagery); 1 fjord and highland (terse; sea, frost, oath-rings,
// ravens, skalds, kennings); 2 heartland and imperial (homely; hearth, kettle, bread, harvest, market, parish);
// 3 dune and sun-temple (ornate; the guest, salt and bread, wells, stars, the sun's eye, shade); 4 steppe (clipped; sky,
// grass, horse, wind, felt and fire); 5 marsh and river (wry; water, reeds, eels, fog, boards, tides, herons);
// 6 jade (formal; this humble one, ancestors, face, propriety, tea, heaven); 7 sylvan and starspire (lyrical; old
// trees, roots, leaves, stars, moon, song).
#include <vector>

namespace story {
namespace saga {
namespace voicedata {

namespace {

const char* const kGreet = R"VOICE(
= greet
F0 NEW FACE. DON'T SEE MANY OF THOSE IN {HOME}.
F0 YOU'LL BE THE STRANGER EVERYONE'S TALKING ABOUT.
F0 STAY A MOMENT, IF YOU'VE A MOMENT.
A0 WELL MET.
A0 HELLO THERE.
A0 AH, A STRANGER.
B0 NOT MANY NEW FACES COME THROUGH {HOME}.
B0 YOU LOOK LIKE YOU'VE WALKED A WAY.
B0 SIT, IF YOU LIKE. THE BENCH IS FREE.
B0 MIND THE MUD. IT GETS EVERYONE.
F1 YOU HAVE THE SALT OF A LONG ROAD ON YOU. SIT.
F1 A STRANGER AT THE DOOR. THE GODS SEND STRANGERS.
F1 HAIL, WANDERER. SHUT THE DOOR. THE COLD LISTENS.
A1 HAIL.
A1 WELL MET, WANDERER.
A1 HAIL, ROAD-WALKER.
B1 THE FIRE IS WARM AND THE ALE IS THIN.
B1 YOUR BOOTS HAVE DRUNK A LOT OF ROAD.
B1 SPEAK, AND I WILL WEIGH IT.
B1 YOU HAVE A SWORD-HAND. I SEE IT.
F2 COME IN OUT OF THE WEATHER. KETTLE'S JUST BOILED.
F2 GOOD DAY TO YOU. YOU'LL WANT DIRECTIONS, I EXPECT.
F2 WELL NOW. A STRANGER IN {HOME}. MIND YOUR PURSE.
A2 GOOD DAY TO YOU.
A2 WELL NOW.
A2 BLESS ME, A STRANGER.
B2 THERE'S BREAD ON THE TABLE IF YOU'RE HUNGRY.
B2 YOU'VE THE LOOK OF SOMEONE WHO WALKED HERE.
B2 WE'RE PLAIN FOLK IN {HOME}, BUT FRIENDLY.
B2 WIPE YOUR BOOTS AND SAY YOUR PIECE.
F3 PEACE ON YOUR ROAD, GUEST. THE WATER HERE IS SWEET.
F3 THE SUN HAS BROUGHT ME A GUEST. SIT IN MY SHADE.
F3 BE WELCOME. NO ONE ASKS A GUEST'S BUSINESS FIRST.
A3 PEACE UPON YOU.
A3 O TRAVELLER,
A3 BE WELCOME, GUEST.
B3 SALT AND BREAD ARE YOURS UNDER THIS ROOF.
B3 SHARE MY WATER BEFORE YOU SHARE YOUR NEWS.
B3 MAY YOUR SHADOW NEVER GROW SHORT.
B3 THE SAND HAS MARKED YOUR FACE. REST.
F4 RIDER OR WALKER? WALKER. STRANGE. SIT.
F4 THE WIND SAID SOMEONE WAS COMING. SIT.
F4 YOU CAME ON FOOT? THE GRASS IS WIDE. DRINK.
A4 SKY KEEP YOU.
A4 GOOD GRASS TO YOU.
A4 STRANGER.
B4 DRINK FIRST. TALK AFTER.
B4 NO HORSE? HM.
B4 THE FIRE IS DUNG, BUT IT IS WARM.
B4 SPEAK SHORT. THE DAY IS LONG.
F5 MIND THE BOARDS, THEY'RE SOFT. NEW FACE, ISN'T IT?
F5 YOU CAME BY ROAD? BRAVE. MOST COME BY BOAT.
F5 THE FOG BROUGHT YOU, DID IT? IT BRINGS ALL SORTS.
A5 WELL, THEN.
A5 AH, A DRY-FOOT.
A5 HELLO, STRANGER.
B5 WIPE THE MUD OFF. NO, THE OTHER MUD.
B5 THERE'S EEL IN THE POT IF YOU'RE BRAVE.
B5 THE HERONS SAW YOU BEFORE I DID.
B5 SIT. THE BOARDS HOLD, MOSTLY.
F6 HONOURED STRANGER, THIS HUMBLE ONE GREETS YOU.
F6 PLEASE, BE SEATED. THE TEA IS POOR, BUT IT IS HOT.
F6 YOU HONOUR {HOME} BY WALKING ITS STREETS.
A6 HONOURED GUEST.
A6 GREETINGS, ESTEEMED TRAVELLER.
A6 FORGIVE THIS INTRUSION.
B6 MAY YOUR ANCESTORS WALK BESIDE YOU.
B6 THIS ONE IS AT YOUR SERVICE.
B6 THE TEA IS POOR, BUT IT IS OFFERED GLADLY.
B6 YOU HAVE COME FAR. IT SHOWS, IF I MAY SAY.
F7 A NEW SONG WALKS UNDER OUR BOUGHS. WELCOME.
F7 THE LEAVES WHISPERED OF YOU BEFORE YOU CAME.
F7 YOU WALK LIKE ONE WHO HAS SEEN MANY STARS SET.
A7 STARLIGHT ON YOUR PATH.
A7 BE WELCOME, WANDERER.
A7 WELL MET UNDER THE BOUGH.
B7 THE OLD TREES DO NOT MIND A GUEST.
B7 REST. THE ROOTS WILL HOLD YOU.
B7 YOUR STEPS ARE LOUD. YOU ARE YOUNG, THEN.
B7 SIT A WHILE. THE STARS ARE IN NO HURRY.
)VOICE";

const char* const kWelcome = R"VOICE(
= welcome
F0 YOU CAME BACK. I WASN'T SURE YOU WOULD.
F0 THERE YOU ARE. I'D STARTED TO WORRY.
F0 BACK AGAIN, AND IN ONE PIECE.
A0 YOU'RE BACK.
A0 THERE YOU ARE.
A0 AH, {PLAYER}.
B0 COME IN, SHUT THE DOOR.
B0 SIT DOWN BEFORE YOU FALL DOWN.
B0 I KEPT YOUR SEAT.
B0 TELL ME EVERYTHING.
F1 THE ROAD GAVE YOU BACK. IT DOESN'T ALWAYS.
F1 YOU AGAIN, AND STILL BREATHING. GOOD.
F1 THE DOOR KNEW YOUR KNOCK.
A1 HAIL, {PLAYER}.
A1 BACK FROM THE COLD.
A1 SO. YOU LIVE.
B1 THE HORN IS FULL. DRINK.
B1 SIT BY THE FIRE AND THAW.
B1 SPEAK. I HAVE WAITED.
B1 THE RAVENS SAID NOTHING. I HOPED.
F2 THERE YOU ARE! I'VE KEPT THE POT ON FOR YOU.
F2 LOOK WHAT THE ROAD DRAGGED IN. COME HERE.
F2 BACK AT LAST. SIT. EAT FIRST, TALK AFTER.
A2 THERE'S MY TRAVELLER.
A2 WELL, LOOK AT YOU.
A2 {PLAYER}! COME IN.
B2 THE KETTLE'S ON.
B2 MIND THE STEP, IT STILL WOBBLES.
B2 YOUR CHAIR'S WHERE YOU LEFT IT.
B2 YOU'VE GONE THIN ON THE ROAD.
F3 THE GUEST RETURNS, AND THE HOUSE IS WHOLE AGAIN.
F3 BLESSED THE DAY THAT BRINGS YOU BACK TO MY DOOR.
F3 YOUR CUP WAS NEVER EMPTIED. SIT.
A3 PEACE UPON YOUR RETURN.
A3 O RETURNING GUEST,
A3 PEACE, {PLAYER}.
B3 MY WATER IS YOUR WATER STILL.
B3 THE STARS KEPT YOUR PLACE.
B3 COME INTO THE SHADE.
B3 I HAVE COUNTED THE DAYS.
F4 YOU CAME BACK OVER THE GRASS. GOOD.
F4 BACK. I SAID YOU WOULD. NOBODY BELIEVED.
F4 THE DOGS KNEW YOU BEFORE I DID.
A4 BACK.
A4 SO. {PLAYER}.
A4 THE WIND RETURNS YOU.
B4 DRINK. THEN TALK.
B4 SIT BY THE FIRE.
B4 THE HORSES REMEMBER YOU.
B4 I KEPT MEAT FOR YOU.
F5 BACK ON DRY BOARDS? WELL, DRYISH.
F5 THE TIDE BRINGS EVERYTHING BACK. EVEN YOU.
F5 THERE YOU ARE. THE HERONS SAID YOU'D COME.
A5 WELL, LOOK.
A5 BACK, ARE YOU?
A5 WELL NOW, {PLAYER}.
B5 THE POT'S STILL ON.
B5 MIND THE SOFT PLANK.
B5 COME IN OUT OF THE DAMP.
B5 YOU SMELL OF THE ROAD. GOOD.
F6 YOUR RETURN HONOURS THIS HOUSE, {PLAYER}.
F6 THIS ONE HAS AWAITED YOUR RETURN WITH RESPECT.
F6 YOU RETURN, AND THE ANCESTORS ARE PLEASED.
A6 HONOURED FRIEND.
A6 WELCOME BACK, ESTEEMED ONE.
A6 HONOURED {PLAYER}.
B6 THE TEA IS ALREADY POURED.
B6 PLEASE, TAKE THE SEAT OF HONOUR.
B6 THIS HOUSE REMEMBERS ITS FRIENDS.
B6 YOUR ROAD WAS LONG. REST.
F7 THE TREES SAID YOU WOULD RETURN. THEY ARE PATIENT.
F7 YOU COME BACK LIKE SPRING: LATE, BUT TRUE.
F7 AH. THE SONG I WAS MISSING.
A7 WELCOME HOME, WANDERER.
A7 YOU RETURN.
A7 {PLAYER}, AT LAST.
B7 SIT UNDER THE BOUGH.
B7 THE STARS KEPT WATCH FOR YOU.
B7 REST. YOUR FEET ARE TIRED OF ROADS.
B7 THE GLADE IS GLAD.
)VOICE";

const char* const kPlea = R"VOICE(
= plea
F0 THERE IS NOBODY ELSE I CAN ASK.
F0 I'D DO IT MYSELF IF I COULD. I CAN'T.
F0 I HAVE NO RIGHT TO ASK. I'M ASKING.
A0 PLEASE.
A0 I'LL NOT PRETEND.
A0 LISTEN TO ME.
F1 I DO NOT ASK TWICE. I DO NOT ASK AT ALL. NOW I ASK.
F1 MY OWN ARM IS NOT ENOUGH. LEND ME YOURS.
F1 THE SKALDS NEED NOT KNOW I BEGGED. HELP ME.
A1 HEAR ME.
A1 I SAY IT ONCE.
A1 NO SKALD WILL SING THIS:
F2 I'D NOT ASK IF THERE WERE ANYONE ELSE. THERE ISN'T.
F2 I CAN'T PAY MUCH, BUT I'LL FEED YOU FOR LIFE.
F2 I'M ONLY A PLAIN BODY. I CAN'T DO THIS ALONE.
A2 PLEASE, I BEG YOU.
A2 I'LL SAY IT STRAIGHT.
A2 YOU LOOK A KIND SORT.
F3 I ASK BY THE SALT WE SHARED. DO NOT REFUSE ME.
F3 A GUEST MAY BE ASKED ONE THING. I ASK IT NOW.
F3 BY THE STARS THAT GUIDE CARAVANS, HELP ME.
A3 O GUEST, HEAR ME.
A3 BY THE SALT WE SHARED,
A3 FORGIVE MY BOLDNESS.
F4 I DO NOT BEG. TODAY I BEG.
F4 ONE RIDER IS NOTHING. TWO IS A RAID. COME.
F4 MY HORSE IS LAME AND MY ARM IS OLD. STAND FOR ME.
A4 HEAR IT.
A4 SHORT WORDS:
A4 LISTEN.
F5 THE WATER'S OVER MY HEAD ON THIS ONE. HELP ME.
F5 I'M ASKING. ME. ASK ANYONE: I NEVER ASK.
F5 I'D SEE TO IT MYSELF IF MY HANDS WERE STEADY.
A5 LOOK.
A5 I'LL NOT DRESS IT UP.
A5 BE A FRIEND TO ME.
F6 THIS UNWORTHY ONE BEGS YOUR AID.
F6 IT SHAMES ME TO ASK. IT WOULD SHAME ME MORE NOT TO.
F6 I ASK NOT FOR MYSELF, BUT FOR MY ANCESTORS.
A6 FORGIVE THIS IMPOSITION.
A6 HONOURED ONE,
A6 WITH RESPECT,
F7 EVEN THE OAK LEANS ON THE WIND. LET ME LEAN ON YOU.
F7 I HAVE SUNG TO THE STARS. NOW I ASK YOU.
F7 MY ROOTS ARE TOO DEEP TO MOVE. BE MY HANDS.
A7 HEAR ME, WANDERER.
A7 GENTLE ONE,
A7 I ASK IT SOFTLY:
Mfear I'M TOO AFRAID TO FACE IT MYSELF.
Mfear I DARE NOT ACT, AND I DARE NOT WAIT.
Mfear I HAVEN'T SLEPT. HELP ME.
Mgreed THERE'S PROFIT IN IT FOR BOTH OF US.
Mgreed HELP ME AND I'LL MAKE IT WORTH YOUR WHILE.
Mgreed NAME A PRICE. I'LL TRY TO MEET IT.
Mgrief I HAVE LOST TOO MUCH ALREADY.
Mgrief I'VE NOTHING LEFT BUT THIS. HELP ME.
Mgrief DON'T LET ME LOSE THIS TOO.
Mpride I'D DO IT MYSELF, IF I WERE YOUNGER.
Mpride IT COSTS ME TO ASK. MARK THAT.
Mpride I DON'T BEG. CALL THIS A BARGAIN.
Mdevotion THE GODS SENT YOU. I'M SURE OF IT.
Mdevotion I PRAYED FOR HELP, AND HERE YOU ARE.
Mdevotion DO IT FOR {GIVER.GOD}, IF NOT FOR ME.
Mlove DO IT FOR THE ONES I LOVE.
Mlove IT'S FOR SOMEONE I LOVE. HELP ME.
Mlove I'D GIVE ANYTHING. ANYTHING.
Mduty SOMEONE MUST, AND I'M BOUND HERE.
Mduty IT'S MY CHARGE, AND I CAN'T LEAVE IT.
Mduty I'M SWORN TO STAY. YOU'RE NOT.
Mvengeance HELP ME SET THIS RIGHT.
Mvengeance I WANT IT ANSWERED. HELP ME.
Mvengeance I'LL NOT REST TILL IT'S PAID FOR.
Mshame I CAN'T FACE IT. YOU CAN.
Mshame IT SHAMES ME TO ASK. I'M ASKING.
Mshame DON'T ASK ME WHY. JUST HELP.
Mhope YOU MIGHT BE THE ONE WHO CAN.
Mhope THERE'S STILL TIME, IF YOU GO.
Mhope IT'S NOT TOO LATE. SAY IT ISN'T.
)VOICE";

const char* const kUrgency = R"VOICE(
= urgency
F0 THERE ISN'T MUCH TIME.
F0 EVERY HOUR COUNTS NOW.
F0 IF IT'S TOMORROW, IT'S TOO LATE.
A0 HURRY.
A0 DON'T DAWDLE.
A0 QUICKLY NOW.
F1 THE TIDE WILL NOT WAIT, AND NEITHER CAN WE.
F1 BEFORE THE ICE CLOSES THE ROAD. GO.
F1 THE RAVENS ARE ALREADY GATHERING.
A1 GO NOW.
A1 NO MORE TALK.
A1 SWIFTLY.
F2 THE BREAD'S BURNING WHILE WE TALK.
F2 BY SUPPERTIME IT'LL BE TOO LATE.
F2 NO TIME TO FETCH THE REEVE. YOU'LL HAVE TO DO.
A2 QUICKLY, NOW.
A2 DON'T STAND THERE.
A2 OFF YOU GO.
F3 THE SAND IN THE GLASS RUNS LOW.
F3 BEFORE THE SUN STANDS HIGH, IT MUST BE DONE.
F3 A CARAVAN THAT WAITS DIES OF THIRST.
A3 MAKE HASTE, GUEST.
A3 SWIFTLY, BY THE SUN.
A3 DO NOT TARRY.
F4 RIDE NOW. TALK LATER.
F4 THE GRASS DOES NOT WAIT FOR SLOW HORSES.
F4 BY NIGHTFALL IT IS DONE, OR LOST.
A4 GO.
A4 NOW.
A4 FAST.
F5 THE WATER'S RISING. IT WON'T WAIT ON US.
F5 BEFORE THE FOG COMES IN. GO.
F5 THE TIDE TURNS SOON, AND IT TURNS HARD.
A5 SHIFT YOURSELF.
A5 QUICK, NOW.
A5 NO TIME.
F6 FORGIVE MY HASTE. THERE IS NO TIME FOR CEREMONY.
F6 EVERY HOUR LOST SHAMES US BOTH.
F6 EVEN THE MAGISTRATE WOULD RUN TODAY.
A6 FORGIVE MY HASTE.
A6 WITHOUT DELAY,
A6 PLEASE, QUICKLY.
F7 EVEN THE SLOW TREES FEEL IT. HURRY.
F7 THE STARS ARE TURNING. WE ARE NOT.
F7 BEFORE THE MOON SETS. GO NOW.
A7 SWIFTLY, WANDERER.
A7 RUN, LIGHT-FOOT.
A7 DO NOT LINGER.
Mfear SOMETHING TERRIBLE IS COMING.
Mfear I CAN FEEL IT CLOSING IN.
Mfear EVERY HOUR MAKES IT WORSE.
Mgreed SOMEONE ELSE WILL GET THERE FIRST.
Mgreed WAIT AND THE CHANCE IS GONE.
Mgreed LATE IS THE SAME AS NOTHING.
Mgrief I CAN'T LOSE ANYTHING ELSE.
Mgrief I WAS TOO LATE ONCE. NOT AGAIN.
Mgrief I'VE WAITED LONG ENOUGH.
Mpride I'LL NOT BE MADE TO LOOK SLOW.
Mpride THEY'LL LAUGH IF WE'RE LATE.
Mpride FIRST OR NOTHING.
Mdevotion THE GODS DON'T WAIT ON US.
Mdevotion IT MUST BE DONE BEFORE THE NEXT PRAYERS.
Mdevotion {GIVER.GOD} IS WATCHING THE HOUR.
Mlove SOMEONE I LOVE IS WAITING ON THIS.
Mlove EVERY HOUR COUNTS, FOR THOSE I LOVE.
Mlove I'D RUN THERE MYSELF IF I COULD.
Mduty IT SHOULD HAVE BEEN DONE YESTERDAY.
Mduty THE WATCH CHANGES SOON. GO.
Mduty I SWORE IT WOULD BE DONE IN TIME.
Mvengeance THE TRAIL IS STILL WARM.
Mvengeance BEFORE THEY GET AWAY WITH IT.
Mvengeance STRIKE WHILE THEY THINK THEY'RE SAFE.
Mshame BEFORE ANYONE ELSE FINDS OUT.
Mshame BEFORE IT COMES OUT. PLEASE.
Mshame I SHOULD HAVE ACTED SOONER.
Mhope THERE'S STILL TIME. JUST.
Mhope IT CAN STILL BE SAVED.
Mhope IF WE GO NOW, WE MIGHT YET.
)VOICE";

const char* const kThanks = R"VOICE(
= thanks
F0 I WON'T FORGET THIS.
F0 THANK YOU. I MEAN IT.
F0 I DON'T KNOW HOW TO REPAY THAT.
A0 THANK YOU.
A0 BLESS YOU.
A0 I MEAN THIS:
F1 YOU HAVE MY THANKS, AND THAT IS NOT NOTHING.
F1 THE SKALDS WILL HEAR OF THIS. I WILL TELL THEM.
F1 A DEBT. I PAY MY DEBTS.
A1 YOU HAVE MY THANKS.
A1 YOU DID WELL.
A1 A GIFT CALLS FOR A GIFT.
F2 THERE'S A PLACE AT MY TABLE FOR YOU. ALWAYS.
F2 YOU'LL NOT PAY FOR BREAD IN THIS HOUSE AGAIN.
F2 BLESS YOU. BLESS WHOEVER RAISED YOU.
A2 THANK YOU KINDLY.
A2 BLESS YOUR HEART.
A2 OH, THANK YOU.
F3 MAY YOUR WELLS NEVER RUN DRY. I AM IN YOUR DEBT.
F3 MY HOUSE IS YOUR HOUSE UNTIL THE STARS FALL.
F3 I WILL WRITE YOUR NAME ON THE WELL-STONE.
A3 A THOUSAND THANKS.
A3 BY THE SUN,
A3 O GENEROUS ONE,
F4 GOOD. YOU ARE GOOD. I SAY IT ONCE.
F4 MY FIRE IS YOUR FIRE NOW.
F4 I OWE YOU A HORSE. I WILL FIND ONE.
A4 GOOD.
A4 THANKS.
A4 YOU DID IT.
F5 I OWE YOU, AND I'M NOT ONE TO OWE.
F5 THERE'S EEL FOR YOU HERE ANY NIGHT.
F5 YOU'VE A FRIEND ON THE WATER NOW.
A5 WELL, THEN.
A5 THANK YOU, TRULY.
A5 I'LL SAY IT:
F6 THIS DEBT WILL BE RECORDED IN THE FAMILY BOOK.
F6 MY ANCESTORS BOW TO YOU, AND SO DO I.
F6 I AM UNWORTHY OF SUCH KINDNESS.
A6 THIS ONE IS GRATEFUL.
A6 PLEASE ACCEPT MY THANKS.
A6 WITH DEEPEST RESPECT,
F7 THE TREES WILL REMEMBER THIS LONGER THAN I WILL.
F7 YOU HAVE PUT A NEW SONG IN ME.
F7 LET THE STARS COUNT THIS IN YOUR FAVOUR.
A7 THANK YOU, KIND ONE.
A7 MY THANKS,
A7 BLESSED BE YOUR STEPS.
Mfear I CAN BREATHE AGAIN BECAUSE OF YOU.
Mfear I'LL SLEEP TONIGHT. THAT'S YOUR DOING.
Mfear YOU WERE BRAVE WHERE I WASN'T.
Mgreed YOU'VE EARNED A CUT. A SMALL ONE.
Mgreed GOOD WORK IS WORTH PAYING FOR.
Mgreed I'LL REMEMBER YOU WHEN PRICES TURN.
Mgrief IT DOESN'T MEND IT. BUT IT HELPS.
Mgrief YOU GAVE ME SOMETHING TO HOLD ON TO.
Mgrief THE DEAD WOULD THANK YOU TOO.
Mpride I'LL ADMIT IT: I COULDN'T HAVE.
Mpride NOT MANY COULD HAVE DONE THAT.
Mpride YOU'VE MADE ME LOOK GOOD. THANK YOU.
Mdevotion {GIVER.GOD} SEES WHAT YOU DID.
Mdevotion I'LL LIGHT A CANDLE FOR YOU.
Mdevotion I PRAYED, AND YOU CAME.
Mlove YOU'VE GIVEN BACK WHAT I LOVE.
Mlove I'LL NEVER BE ABLE TO REPAY YOU.
Mlove MY HEART'S FULL. I CAN'T SAY MORE.
Mduty YOU DID WHAT WAS RIGHT. THANK YOU.
Mduty THE DUTY WAS MINE. YOU CARRIED IT.
Mduty IT'S DONE PROPERLY. THAT MATTERS.
Mvengeance IT'S ANSWERED. THANK YOU FOR THAT.
Mvengeance NOW I CAN SLEEP.
Mvengeance YOU SETTLED IT. I OWE YOU.
Mshame YOU NEEDN'T HAVE. YOU DID ANYWAY.
Mshame I DON'T DESERVE THIS KINDNESS.
Mshame YOU SAVED MY FACE AND MORE.
Mhope YOU'VE GIVEN ME A FUTURE.
Mhope I KNEW YOU WOULD. I KNEW IT.
Mhope THINGS WILL GET BETTER NOW.
)VOICE";

const char* const kFarewell = R"VOICE(
= farewell
F0 GO CAREFULLY.
F0 COME BACK WHOLE.
F0 SAFE ROAD TO YOU.
A0 WELL.
A0 GO ON, THEN.
A0 TAKE CARE.
B0 MIND HOW YOU GO.
B0 THE ROAD'S LONGER THAN IT LOOKS.
B0 COME BACK AND TELL ME.
F1 MAY THE ICE HOLD UNDER YOUR FEET.
F1 GO. AND COME BACK WITH A SONG.
F1 FAIR WINDS, AND A SHORT WINTER.
A1 GO WELL.
A1 FARE WELL, WANDERER.
A1 SO.
B1 KEEP YOUR SHIELD HIGH.
B1 THE COLD CAN HAVE OTHERS. NOT YOU.
B1 MAY THE WOLVES SLEEP.
F2 MIND THE WEATHER. AND EAT SOMETHING.
F2 GO ON, AND COME BACK FOR SUPPER.
F2 SAFE HOME, AS THEY SAY HERE.
A2 OFF YOU GO, THEN.
A2 TAKE CARE, NOW.
A2 GO GENTLY.
B2 WRAP UP WARM.
B2 DON'T PAY A TOLL TWICE.
B2 KEEP TO THE ROAD.
F3 GO IN PEACE, AND RETURN IN PEACE.
F3 MAY YOUR SHADOW BE LONG AND YOUR WATER SWEET.
F3 THE STARS WILL GUIDE YOU. I HAVE ASKED THEM.
A3 GO IN PEACE.
A3 FAREWELL, O GUEST.
A3 PEACE BE ON YOUR ROAD.
B3 MAY THE WELLS BE KIND.
B3 TRAVEL BY STARLIGHT. THE SUN IS CRUEL.
B3 MY DOOR STAYS OPEN.
F4 GOOD GRASS AND A SOUND HORSE.
F4 RIDE WELL. DON'T LOOK BACK.
F4 THE SKY IS WIDE. YOU WILL NOT GET LOST.
A4 GO.
A4 RIDE WELL.
A4 SKY KEEP YOU.
B4 THE WIND IS AT YOUR BACK.
B4 WATCH THE HORIZON.
B4 COME BACK BEFORE THE SNOW.
F5 KEEP YOUR FEET DRY, IF YOU CAN.
F5 THE RIVER GOES WHERE YOU GO. IT'LL WATCH.
F5 MIND THE FOG. IT LIES.
A5 OFF YOU GO.
A5 GO CAREFUL.
A5 WELL, THEN.
B5 STAY ON THE BOARDS.
B5 DON'T DRINK THE STANDING WATER.
B5 COME BACK BY THE HIGH PATH.
F6 MAY YOUR ANCESTORS LIGHT YOUR ROAD.
F6 GO WITH HONOUR, AND RETURN WITH IT.
F6 THIS HUMBLE HOUSE AWAITS YOUR RETURN.
A6 FAREWELL, HONOURED ONE.
A6 GO IN SAFETY.
A6 WITH RESPECT,
B6 WALK WITH PROPRIETY.
B6 MAY HEAVEN BE KIND TO YOU.
B6 THE LANTERN WILL BE LIT FOR YOU.
F7 MAY THE STARS BE KIND TO YOUR FEET.
F7 GO SOFTLY. THE WOOD HEARS EVERYTHING.
F7 UNTIL THE LEAVES TURN AGAIN.
A7 GO WELL, WANDERER.
A7 FAREWELL.
A7 SING ON YOUR ROAD.
B7 THE ROOTS WILL REMEMBER YOUR STEP.
B7 MAY THE MOON WALK BESIDE YOU.
B7 COME BACK BEFORE THE SONG ENDS.
)VOICE";

const char* const kBlessing = R"VOICE(
= blessing
F0 {GIVER.GOD} KEEP YOU.
F0 GOOD LUCK GO WITH YOU.
F0 MAY YOU FIND WHAT YOU'RE AFTER.
A0 GODS KEEP YOU.
A0 LUCK TO YOU.
A0 BE WELL.
B0 AND A DRY BED TONIGHT.
B0 MAY YOUR BOOTS HOLD OUT.
B0 AND A WARM WELCOME WHEREVER YOU GO.
F1 {GIVER.GOD} GUARD YOUR SHIELD-ARM.
F1 MAY YOUR ALE BE STRONG AND YOUR ENEMIES WEAK.
F1 A HOT FIRE AND A HIGH ROOF BE YOURS.
A1 MAY {GIVER.GOD} SEE YOU.
A1 FAIR WIND.
A1 LUCK AND IRON.
B1 MAY YOUR BLADE BITE TRUE.
B1 AND MAY THE SKALDS SING YOU.
B1 MAY THE FROST PASS YOUR DOOR.
F2 MAY YOUR BREAD NEVER GO STALE.
F2 WARM HEARTH, FULL CUP.
F2 {GIVER.GOD} SMILE ON YOUR HARVEST.
A2 BLESS YOU.
A2 {GIVER.GOD} KEEP YOU.
A2 GOOD FORTUNE.
B2 AND A FULL LARDER.
B2 MAY YOUR ROOF NEVER LEAK.
B2 AND KIND NEIGHBOURS WHEREVER YOU GO.
F3 MAY {GIVER.GOD} SET A STAR OVER YOUR TENT.
F3 MAY YOUR SHADOW NEVER SHORTEN.
F3 SWEET WELLS AND COOL NIGHTS BE YOURS.
A3 {GIVER.GOD} SHADE YOU.
A3 BY THE SUN'S EYE,
A3 PEACE AND WATER.
B3 MAY YOUR WELLS RUN DEEP.
B3 MAY THE DUNES LIE STILL FOR YOU.
B3 MAY YOUR CARAVAN COME HOME FULL.
F4 MAY YOUR HORSE NEVER STUMBLE.
F4 {GIVER.GOD} WATCH YOU FROM THE WIDE SKY.
F4 GOOD GRASS UNDER YOU, OPEN SKY ABOVE.
A4 SKY KEEP YOU.
A4 {GIVER.GOD} SEE YOU.
A4 LUCK.
B4 MAY YOUR ARROWS FLY STRAIGHT.
B4 MAY YOUR HERDS GROW.
B4 AND A WARM FELT ROOF AT NIGHT.
F5 MAY THE RIVER CARRY YOU AND NOT KEEP YOU.
F5 {GIVER.GOD} KEEP YOUR BOAT UPRIGHT.
F5 DRY FEET AND A FULL NET.
A5 RIVER KEEP YOU.
A5 TIDE TURN FOR YOU.
A5 {GIVER.GOD} KEEP YOU DRY.
B5 MAY THE EELS BITE.
B5 MAY THE FOG LIFT FOR YOU.
B5 AND SOUND BOARDS UNDERFOOT.
F6 MAY YOUR ANCESTORS SMILE UPON YOUR NAME.
F6 LONG LIFE AND AN HONOURED NAME.
F6 MAY HEAVEN GRANT YOU A PEACEFUL ROAD.
A6 MAY HEAVEN SMILE.
A6 {GIVER.GOD} PROTECT YOU.
A6 WITH RESPECT,
B6 LONG LIFE TO YOUR HOUSE.
B6 MAY YOUR NAME BE WRITTEN IN JADE.
B6 MAY YOUR CHILDREN PROSPER.
F7 MAY THE STARS LIGHT YOUR WAY HOME.
F7 {GIVER.GOD} KEEP YOU UNDER THE LEAF.
F7 MAY YOU NEVER WALK WHERE NO TREE GROWS.
A7 STARLIGHT ON YOU.
A7 {GIVER.GOD} BLESS YOUR ROOTS.
A7 BE BLESSED.
B7 MAY THE OLD TREES SHELTER YOU.
B7 AND A SOFT MOSS BED.
B7 MAY YOUR SONG OUTLAST YOU.
)VOICE";

const char* const kOath = R"VOICE(
= oath
F0 BY {GIVER.GOD}, I SWEAR IT.
F0 ON MY MOTHER'S GRAVE.
F0 I SWEAR IT ON ALL I HAVE.
A0 I SWEAR IT.
A0 ON MY LIFE.
A0 BY {GIVER.GOD}.
B0 LET ME ROT IF I LIE.
B0 STRIKE ME DOWN IF IT'S FALSE.
B0 AND I DON'T SWEAR LIGHTLY.
F1 ON THE OATH-RING, AND BEFORE {GIVER.GOD}.
F1 BY ICE AND IRON, I SWEAR IT.
F1 MAY MY CAIRN STAND EMPTY IF I LIE.
A1 BY ICE AND IRON.
A1 ON THE RING.
A1 BEFORE {GIVER.GOD} AND THE ICE.
B1 LET THE SEA TAKE ME IF I LIE.
B1 MY BLOOD ON IT.
B1 LET THE RAVENS HAVE MY EYES ELSE.
F2 MAY MY HEARTH GO COLD IF I LIE.
F2 ON MY FATHER'S PLOUGH, I SWEAR IT.
F2 AS {GIVER.GOD} WATCHES THE HARVEST, I SWEAR.
A2 AS I STAND HERE,
A2 HAND ON HEART.
A2 BY {GIVER.GOD} AND THE HARVEST.
B2 MAY MY BREAD TURN TO STONE ELSE.
B2 AND MAY THE BLIGHT TAKE ME IF NOT.
B2 ON EVERYTHING I OWN.
F3 BY SALT AND BREAD AND {GIVER.GOD}, I SWEAR IT.
F3 BY THE SUN'S OPEN EYE, IT IS TRUE.
F3 MAY THE WELL DRY UNDER MY HAND IF I LIE.
A3 BY THE SUN'S EYE.
A3 BY SALT AND BREAD.
A3 BEFORE {GIVER.GOD}.
B3 MAY THE SAND TAKE MY NAME ELSE.
B3 LET MY SHADOW FAIL ME IF I LIE.
B3 I SWEAR IT ON MY FATHERS' WELLS.
F4 BY THE OPEN SKY. I DO NOT LIE.
F4 ON MY HORSE'S HEAD, I SWEAR IT.
F4 LET THE GRASS GROW OVER ME IF I LIE.
A4 BY THE SKY.
A4 ON MY BOW.
A4 UNDER {GIVER.GOD}'S SKY.
B4 TRUE AS AN ARROW.
B4 MY WORD IS A TETHER.
B4 LET THE WIND SCATTER MY ASHES ELSE.
F5 ON THE RIVER, AND IT HEARS EVERYTHING.
F5 MAY THE MUD HAVE ME IF I LIE.
F5 BY {GIVER.GOD} AND THE DEEP WATER.
A5 ON THE RIVER.
A5 BY THE DEEP WATER.
A5 BY {GIVER.GOD} OF THE WATERS.
B5 LET THE EELS HAVE ME ELSE.
B5 AND THE RIVER KEEPS ACCOUNTS.
B5 MAY I DROWN IN A PUDDLE IF NOT.
F6 BY MY ANCESTORS' TABLETS, I SWEAR IT.
F6 IF I LIE, STRIKE MY NAME FROM THE FAMILY BOOK.
F6 BEFORE HEAVEN AND {GIVER.GOD}, IT IS TRUE.
A6 BY MY ANCESTORS.
A6 BEFORE HEAVEN.
A6 ON MY FAMILY'S NAME.
B6 THIS ONE DOES NOT LIE.
B6 LET MY FACE BE LOST IF I LIE.
B6 MAY MY LINE END IF IT IS FALSE.
F7 BY ROOT AND STAR, I SWEAR IT.
F7 MAY THE OLD TREES FORGET MY NAME IF I LIE.
F7 UNDER THE STARS OF {GIVER.GOD}, IT IS TRUE.
A7 BY ROOT AND STAR.
A7 BY THE ELDEST TREE.
A7 UNDER {GIVER.GOD}.
B7 THE LEAVES ARE MY WITNESS.
B7 LET MY SONG FAIL IF I LIE.
B7 AS SURE AS SPRING.
)VOICE";

const char* const kVow = R"VOICE(
= vow
F0 I'LL SEE IT DONE.
F0 YOU HAVE MY WORD ON IT.
F0 I WON'T REST UNTIL IT'S FINISHED.
A0 MARK ME.
A0 I PROMISE YOU.
A0 LISTEN:
F1 I WILL DO IT, OR LET THE SKALDS CALL ME COWARD.
F1 IT WILL BE DONE BEFORE THE THAW.
F1 I HAVE SAID IT. NOW IT IS IRON.
A1 HEAR MY VOW.
A1 BY MY ARM,
A1 SAID IS DONE.
F2 I'LL SEE IT DONE IF IT TAKES ALL WINTER.
F2 MY WORD'S GOOD. ASK ANYONE IN {HOME}.
F2 IT'LL BE DONE, AND DONE PROPER.
A2 AS SURE AS BREAD,
A2 I'LL TELL YOU THIS:
A2 HAND ON HEART,
F3 AS THE SUN RISES, SO WILL I DO THIS.
F3 I GIVE YOU MY WORD BEFORE THE STARS.
F3 IT IS PROMISED. THE SAND HAS HEARD IT.
A3 I PROMISE BY THE STARS.
A3 HEAR ME, GUEST.
A3 BEFORE THE SUN,
F4 I SAY IT. IT WILL BE.
F4 BEFORE THE NEXT MOON, IT IS DONE.
F4 MY WORD IS AN ARROW. IT FLIES ONCE.
A4 I SAY IT.
A4 HEAR.
A4 MY WORD:
F5 IT'LL BE DONE, SLOW AS THE RIVER BUT AS SURE.
F5 I'LL DO IT. THE HERONS ARE MY WITNESS.
F5 YOU HAVE MY WORD, AND IT DOESN'T SINK.
A5 MARK IT.
A5 I'LL SAY IT ONCE.
A5 ON THE WATER,
F6 IT WILL BE DONE, OR I WILL HAVE NO FACE LEFT.
F6 THIS ONE PLEDGES IT, BEFORE THE ANCESTORS.
F6 I WILL NOT FAIL. MY FATHERS DID NOT.
A6 I PLEDGE IT.
A6 BEFORE MY ANCESTORS,
A6 UPON MY HONOUR,
F7 AS THE ROOT HOLDS, SO WILL I.
F7 I WILL SEE IT DONE, THOUGH IT TAKE A HUNDRED YEARS.
F7 MY PROMISE IS A SEED. IT WILL GROW.
A7 I PROMISE IT.
A7 UNDER THE STARS,
A7 HEAR ME, WANDERER.
Mfear I'LL DO MY PART, FRIGHTENED OR NOT.
Mfear I'M AFRAID. I'LL DO IT ANYWAY.
Mfear MY HANDS SHAKE, BUT THEY'LL HOLD.
Mgreed I'LL PAY WHAT'S OWED. EVERY COIN.
Mgreed WHEN IT'S DONE, YOU'LL HAVE YOUR SHARE.
Mgreed I DON'T BREAK A GOOD BARGAIN.
Mgrief I'LL KEEP THEIR MEMORY. ALWAYS.
Mgrief I'LL NOT LET IT BE FORGOTTEN.
Mgrief I'LL CARRY THIS FOR THE DEAD.
Mpride NOBODY WILL SAY I FAILED.
Mpride I'VE NEVER BROKEN MY WORD. NOT ONCE.
Mpride WATCH ME DO IT.
Mdevotion {GIVER.GOD} WILL SEE ME KEEP IT.
Mdevotion I'LL KEEP FAITH, WHATEVER IT COSTS.
Mdevotion I'LL PRAY, AND THEN I'LL ACT.
Mlove FOR THOSE I LOVE, I'D DO ANYTHING.
Mlove I'LL NOT LEAVE THEIR SIDE AGAIN.
Mlove I'LL MAKE IT RIGHT. FOR THEM.
Mduty IT'S MY CHARGE. I'LL CARRY IT.
Mduty I'LL STAND MY POST TO THE END.
Mduty IT WILL BE DONE AS IT SHOULD BE.
Mvengeance THEY WILL ANSWER FOR IT.
Mvengeance I'LL NOT FORGET. NOT EVER.
Mvengeance IT WILL BE PAID IN FULL.
Mshame I'LL MAKE AMENDS. ALL OF THEM.
Mshame I'LL MEND WHAT I BROKE.
Mshame I'LL EARN BACK MY NAME.
Mhope WE'LL SEE BETTER DAYS. I'LL MAKE THEM.
Mhope I'LL BUILD IT AGAIN, BETTER.
Mhope THIS WON'T BE THE END OF IT.
)VOICE";

const char* const kPraise = R"VOICE(
= praise
F0 THAT WAS WELL DONE. TRULY.
F0 NOT MANY WOULD HAVE DONE THAT.
F0 YOU'VE A GOOD HEART, AND A STRONG ARM.
A0 WELL DONE.
A0 LOOK AT YOU.
A0 I'LL SAY THIS:
B0 THEY'LL TALK ABOUT IT FOR YEARS.
B0 YOU DID IT PROPERLY.
B0 I'D NOT HAVE BELIEVED IT.
F1 THE SKALDS WILL HAVE A NEW SONG.
F1 THAT DEED WILL OUTLIVE US BOTH.
F1 A DEED FOR THE MEAD-BENCH, THAT.
A1 HAH! WELL DONE.
A1 HAIL, {PLAYER}.
A1 A GOOD DEED.
B1 YOUR NAME WILL BE SUNG.
B1 THE GODS SAW IT.
B1 THE HALL WILL DRINK TO YOU.
F2 WELL DONE, YOU. WELL DONE INDEED.
F2 WHOEVER RAISED YOU WOULD BE PROUD.
F2 THAT'S A DEED WORTH A SUPPER.
A2 WELL DONE, YOU.
A2 BLESS YOU,
A2 WELL I NEVER.
B2 THE WHOLE VILLAGE WILL HEAR OF IT.
B2 YOU'VE EARNED A SEAT BY THE FIRE.
B2 THAT'S PROPER WORK.
F3 THE POETS WILL WRITE OF THIS.
F3 YOUR NAME SHALL BE SPOKEN AT EVERY WELL.
F3 TRULY, THE STARS CHOSE WELL IN YOU.
A3 O MARVEL,
A3 BY THE SUN,
A3 BEHOLD:
B3 YOUR DEED SHINES LIKE NOON.
B3 THE CARAVANS WILL SING IT.
B3 YOUR FATHERS SMILE TODAY.
F4 GOOD. VERY GOOD. I SAY IT TWICE.
F4 A DEED FOR THE CAMPFIRES.
F4 THE HERDERS WILL SPEAK OF THIS.
A4 GOOD.
A4 HAH!
A4 SEE THIS.
B4 YOU RIDE WELL.
B4 THE SKY SAW IT.
B4 STRONG ARM, CLEAR EYE.
F5 NEATLY DONE. LIKE A HERON TAKING A FISH.
F5 THEY'LL TELL OF IT ON EVERY FERRY.
F5 YOU'VE MORE SENSE THAN THE WHOLE MARSH.
A5 WELL, LOOK.
A5 NICELY DONE.
A5 HA! LOOK AT THAT.
B5 THE FERRYMEN WILL HEAR.
B5 CLEAN AS RAIN.
B5 NOT A FOOT WRONG.
F6 YOUR CONDUCT DOES CREDIT TO YOUR ANCESTORS.
F6 SUCH VIRTUE IS RARE. IT WILL BE RECORDED.
F6 THIS HUMBLE ONE IS AWED.
A6 MOST ADMIRABLE.
A6 WITH RESPECT,
A6 TRULY,
B6 YOUR NAME HONOURS ITS HOUSE.
B6 HEAVEN SMILES ON YOU.
B6 IT WILL BE WRITTEN DOWN.
F7 THE STARS LEANED CLOSER TO WATCH YOU.
F7 A DEED TO PLANT A TREE FOR.
F7 THE WOOD WILL SING OF THIS AFTER US.
A7 AH, BRAVELY DONE.
A7 WANDERER,
A7 LOOK:
B7 THE LEAVES APPLAUD.
B7 A NEW VERSE FOR THE OLD SONG.
B7 THE MOON WILL REMEMBER.
)VOICE";

const char* const kComfort = R"VOICE(
= comfort
F0 IT WASN'T YOUR FAULT.
F0 YOU'RE NOT ALONE IN THIS.
F0 SIT. BREATHE. I'M HERE.
A0 HUSH, NOW.
A0 EASY.
A0 LISTEN TO ME.
F1 THE WINTER ENDS. EVEN THIS ONE.
F1 WEEP, THEN. EVEN THE CLIFFS WEEP IN SPRING.
F1 YOU ARE NOT THE FIRST TO CARRY THIS. NOR THE LAST.
A1 HUSH.
A1 EASY, KIN.
A1 SIT BY THE FIRE.
F2 THERE, NOW. THE KETTLE'S ON. IT'LL KEEP.
F2 NOTHING'S SO BAD THAT BREAD CAN'T HELP A LITTLE.
F2 YOU DID ALL ANYONE COULD.
A2 THERE, THERE.
A2 OH, LOVE.
A2 COME HERE.
F3 THE NIGHT IS LONG, BUT THE STARS ARE OUT.
F3 SIT IN THE SHADE. THE SUN WILL STILL BE THERE.
F3 EVEN THE DESERT BLOOMS AFTER RAIN.
A3 PEACE, FRIEND.
A3 BE AT PEACE.
A3 O HEART,
F4 THE STORM PASSES. THE GRASS STANDS UP.
F4 SIT. DRINK. THE SKY IS STILL ABOVE US.
F4 EVEN WOLVES REST.
A4 EASY, RIDER.
A4 SIT.
A4 STILL, NOW.
F5 IT'LL SETTLE, LIKE SILT. GIVE IT TIME.
F5 THE TIDE GOES OUT. IT COMES BACK. YOU WILL TOO.
F5 EVEN THE RIVER LOSES ITSELF IN THE MARSH A WHILE.
A5 EASY, NOW.
A5 THERE.
A5 STILL WATERS.
F6 THERE IS NO SHAME IN GRIEF. SIT.
F6 THE ANCESTORS SEE YOUR HEART. THEY ARE NOT ANGRY.
F6 PLEASE, DRINK THE TEA. SPEAK WHEN YOU CAN.
A6 PLEASE, BE CALM.
A6 HONOURED FRIEND,
A6 GENTLY.
F7 THE LEAVES FALL. THE TREE DOES NOT.
F7 WEEP. THE RAIN DOES, AND THE WOOD IS GREENER.
F7 EVEN THE DARK BETWEEN STARS IS FULL OF LIGHT.
A7 HUSH, LITTLE ONE.
A7 BE STILL.
A7 GENTLY, WANDERER.
Mfear WE'LL FACE IT TOGETHER.
Mfear NOTHING WILL HAPPEN TONIGHT. I'LL WATCH.
Mfear BEING AFRAID ISN'T BEING WEAK.
Mgreed WHAT'S LOST CAN BE EARNED AGAIN.
Mgreed COIN COMES BACK. YOU'RE STILL HERE.
Mgreed WE'LL MAKE IT UP. ALL OF IT.
Mgrief GRIEF IS LOVE WITH NOWHERE TO GO.
Mgrief YOU'LL CARRY IT. IT'LL GET LIGHTER.
Mgrief THE DEAD WOULDN'T WANT YOU LIKE THIS.
Mpride YOU'VE NOTHING TO PROVE TO ME.
Mpride THERE'S NO SHAME IN BEING TIRED.
Mpride YOU DID WELL. BETTER THAN WELL.
Mdevotion {GIVER.GOD} HASN'T FORGOTTEN YOU.
Mdevotion PRAY IF YOU CAN. IF YOU CAN'T, I WILL.
Mdevotion THE GODS KEEP WHAT WE LOSE.
Mlove I'M HERE. I'M NOT GOING ANYWHERE.
Mlove YOU'RE LOVED. THAT DOESN'T CHANGE.
Mlove LEAN ON ME. THAT'S WHAT I'M FOR.
Mduty YOU DID WHAT WAS ASKED. MORE.
Mduty NO ONE COULD HAVE HELD LONGER.
Mduty REST. THE WATCH IS MINE NOW.
Mvengeance IT WILL BE ANSWERED. NOT TONIGHT.
Mvengeance ANGER KEEPS. LET IT SLEEP AWHILE.
Mvengeance IT WON'T GO UNANSWERED. REST.
Mshame WHAT'S DONE IS DONE. YOU'RE MORE THAN IT.
Mshame I DON'T THINK LESS OF YOU.
Mshame EVERYONE FALLS. FEW GET UP.
Mhope IT'S NOT OVER. NOT YET.
Mhope TOMORROW'S A NEW FURROW.
Mhope THERE'S STILL A ROAD AHEAD.
)VOICE";

const char* const kApology = R"VOICE(
= apology
F0 I WAS WRONG. I KNOW THAT NOW.
F0 FORGIVE ME. I DIDN'T KNOW.
F0 I SHOULD HAVE SAID IT SOONER.
A0 I'M SORRY.
A0 LOOK,
A0 FORGIVE ME.
F1 I SPOKE LIKE A FOOL. I UNSAY IT.
F1 MY TONGUE RAN AHEAD OF MY WITS.
F1 I OWE YOU A BLOOD-PRICE OF WORDS. HERE IT IS.
A1 I WAS WRONG.
A1 HEAR THIS.
A1 MY FAULT.
F2 I'M SORRY. TRULY, I AM.
F2 I'VE BEEN A PROPER FOOL.
F2 I'LL MAKE IT UP TO YOU. SOMEHOW.
A2 OH, I'M SORRY.
A2 FORGIVE A FOOL.
A2 I'M ASHAMED.
F3 I HAVE SHAMED MY HOUSE. FORGIVE ME.
F3 MY WORDS WERE SAND IN YOUR CUP. I AM SORRY.
F3 A HOST WHO WRONGS A GUEST IS NOTHING. FORGIVE.
A3 FORGIVE ME, GUEST.
A3 BY THE SUN, I AM SORRY.
A3 I HAVE SHAMED MY HOUSE.
F4 I WAS WRONG. I SAY IT ONCE. I MEAN IT ALWAYS.
F4 MY FAULT. NOT YOURS.
F4 I RODE THE WRONG WAY. I TURN BACK.
A4 WRONG.
A4 I RODE WRONG.
A4 HEAR IT: SORRY.
F5 I'M SORRY. THAT WAS MUDDY OF ME.
F5 I GOT IT WRONG. IT HAPPENS ON THE WATER.
F5 FORGIVE ME. I'LL NOT DO IT AGAIN.
A5 SORRY, NOW.
A5 AH, I'M SORRY.
A5 LOOK HERE,
F6 THIS ONE HAS ERRED, AND BEGS PARDON.
F6 I HAVE LOST FACE BEFORE YOU. FORGIVE ME.
F6 MY CONDUCT WAS UNWORTHY. I APOLOGISE.
A6 PLEASE, FORGIVE ME.
A6 THIS ONE APOLOGISES.
A6 I AM ASHAMED.
F7 I SANG THE WRONG SONG. FORGIVE ME.
F7 I WAS A STORM. I AM SORRY.
F7 EVEN OLD TREES DROP DEAD WOOD. I WAS WRONG.
A7 I SPOKE LIKE A STORM.
A7 THE STARS SAW MY FAULT.
A7 FORGIVE ME, WANDERER.
Mfear I WAS FRIGHTENED. IT'S NO EXCUSE.
Mfear I PANICKED. I'M SORRY.
Mfear FEAR MADE ME SMALL.
Mgreed I WANTED MORE THAN WAS MINE.
Mgreed THE COIN TURNED MY HEAD.
Mgreed I'LL PAY IT BACK, EVERY COIN.
Mgrief GRIEF MADE ME CRUEL.
Mgrief I WASN'T MYSELF. I'M STILL NOT.
Mgrief I TOOK IT OUT ON YOU.
Mpride MY PRIDE SPOKE FOR ME.
Mpride I DIDN'T WANT TO BE WRONG.
Mpride IT COSTS ME TO SAY THIS.
Mdevotion {GIVER.GOD} KNOWS I'VE SINNED.
Mdevotion I'LL DO PENANCE FOR IT.
Mdevotion I FAILED THE GODS AND YOU.
Mlove I DID IT FOR LOVE. IT WAS STILL WRONG.
Mlove I HURT THE ONES I LOVE.
Mlove I'D TAKE IT BACK IF I COULD.
Mduty I FAILED IN MY DUTY.
Mduty I SHOULD HAVE STOOD MY GROUND.
Mduty I'LL ANSWER FOR IT.
Mvengeance I WANTED SOMEONE TO PAY. IT WAS YOU.
Mvengeance MY ANGER WAS AIMED WRONG.
Mvengeance I SAW AN ENEMY. IT WAS A FRIEND.
Mshame I CAN'T LOOK AT YOU.
Mshame I'M ASHAMED OF WHAT I DID.
Mshame I'VE CARRIED THIS TOO LONG.
Mhope LET ME MAKE IT RIGHT.
Mhope CAN WE START AGAIN?
Mhope I'LL DO BETTER. I PROMISE.
)VOICE";

const char* const kRelief = R"VOICE(
= relief
F0 THANK THE GODS.
F0 I CAN BREATHE AGAIN.
F0 IT'S OVER. IT'S REALLY OVER.
A0 OH.
A0 FINALLY.
A0 THANK GOODNESS.
F1 THE STORM HAS PASSED. THE HALL STANDS.
F1 THE ICE HELD. THANK {GIVER.GOD}.
F1 I CAN SLEEP WITHOUT MY AXE TONIGHT.
A1 HAH.
A1 SO. IT HOLDS.
A1 THE GODS ARE KIND.
F2 OH, THANK GOODNESS. I'LL PUT THE KETTLE ON.
F2 WELL, THAT'S A WEIGHT OFF.
F2 I'LL SLEEP IN MY OWN BED TONIGHT.
A2 OH, THANK GOODNESS.
A2 PHEW.
A2 WELL!
F3 THE STORM OF SAND HAS PASSED.
F3 WATER AFTER THIRST. PRAISE {GIVER.GOD}.
F3 THE SUN SMILES AGAIN.
A3 PRAISE THE SUN.
A3 AH, SWEET WATER.
A3 AT LAST, AT LAST.
F4 GOOD. THE WIND DROPPED.
F4 THE HERD IS SAFE. I CAN SIT.
F4 THE SKY CLEARED.
A4 GOOD.
A4 HM. GOOD.
A4 SKY BE THANKED.
F5 THE WATER'S GOING DOWN.
F5 SOLID GROUND AT LAST.
F5 THE FOG'S LIFTED. I CAN SEE AGAIN.
A5 OH, THE RIVER.
A5 WELL, NOW.
A5 THANK THE RIVER.
F6 HEAVEN BE THANKED. ORDER IS RESTORED.
F6 THE ANCESTORS ARE APPEASED.
F6 A GREAT WEIGHT LIFTS FROM THIS HOUSE.
A6 HEAVEN BE THANKED.
A6 AH, HOW FORTUNATE.
A6 AT LONG LAST,
F7 THE DAWN CAME. IT ALWAYS DOES.
F7 THE TREES ARE BREATHING AGAIN.
F7 THE STORM IS GONE. LISTEN TO THE BIRDS.
A7 AH.
A7 THE BOUGHS LIFT.
A7 THE STARS BE THANKED.
Mfear I THOUGHT I'D NEVER STOP SHAKING.
Mfear IT'S GONE. IT'S REALLY GONE.
Mfear I CAN SLEEP TONIGHT.
Mgreed NOTHING'S LOST. NOT A COIN.
Mgreed THE LEDGER BALANCES AGAIN.
Mgreed MY STORES ARE SAFE.
Mgrief AT LEAST THAT'S ENDED.
Mgrief ONE LESS THING TO MOURN.
Mgrief I CAN GRIEVE IN PEACE NOW.
Mpride MY NAME IS CLEAN AGAIN.
Mpride I WAS RIGHT. I KNEW IT.
Mpride NOBODY CAN SAY I FAILED NOW.
Mdevotion {GIVER.GOD} HEARD MY PRAYERS.
Mdevotion THE GODS ARE MERCIFUL.
Mdevotion I'LL MAKE AN OFFERING TONIGHT.
Mlove THAT'S ALL I WANTED. ALL OF IT.
Mlove MY HEART CAN SLOW DOWN NOW.
Mlove MY HEART CAN BEAT AGAIN.
Mduty THE WATCH IS KEPT. IT'S DONE.
Mduty I CAN REPORT IT DONE.
Mduty MY CHARGE IS DISCHARGED.
Mvengeance IT'S ANSWERED. I CAN REST.
Mvengeance THE DEBT'S PAID.
Mvengeance NOW THE DEAD CAN SLEEP.
Mshame NOBODY NEED EVER KNOW.
Mshame I CAN LOOK PEOPLE IN THE EYE.
Mshame THE STAIN'S WASHED OUT.
Mhope I KNEW IT WOULD COME RIGHT.
Mhope THINGS ARE TURNING.
Mhope THERE'S A TOMORROW AGAIN.
)VOICE";

}  // namespace

void socialBlocks(std::vector<const char*>& out) {
  out.push_back(kGreet);
  out.push_back(kWelcome);
  out.push_back(kPlea);
  out.push_back(kUrgency);
  out.push_back(kThanks);
  out.push_back(kFarewell);
  out.push_back(kBlessing);
  out.push_back(kOath);
  out.push_back(kVow);
  out.push_back(kPraise);
  out.push_back(kComfort);
  out.push_back(kApology);
  out.push_back(kRelief);
}

}  // namespace voicedata
}  // namespace saga
}  // namespace story
