// Background generation for the endless world's Active Window (VISION_PLAN 2.8, 12.2). SIM lane, M1.
//
// World asks for the chunks (and region plans) the next window shifts will need; a shift then only copies ready chunks.
//   Native (desktop, iOS): one worker thread with ITS OWN ew::EndlessSource(seed). Generation is a pure function of
//     (seed, coordinates), so the worker's chunks equal what the main thread's source would make. One source instance is
//     not thread-safe, and the main-thread instance is also used by the view, so they are never shared across threads.
//   Web (no pthreads on GitHub Pages): no thread; pump(budgetMs) generates on the main thread with the main source,
//     a chunk at a time, until the frame's budget (about 3 ms) is spent (rpg/world/jobs.h). A settlement under a chunk
//     is built first, a generator phase at a time across frames (EndlessSource::prepareChunk), so a city never costs
//     one frame its whole build (rpg_test --window --web measures it).
// Teleports and loads stay synchronous behind the fade (World::placeWindow generates what is not ready).
#pragma once
#include <cstdint>
#include <memory>
#include <vector>

namespace ew {
struct ChunkData;
struct RegionPlan;
class EndlessSource;
}  // namespace ew

class ChunkStreamer {
 public:
  // threaded: a worker thread (ignored, i.e. false, on the web). mainSrc: the world's own source, used by pump() when
  // there is no worker
  ChunkStreamer(uint64_t seed, std::shared_ptr<ew::EndlessSource> mainSrc, bool threaded);
  ~ChunkStreamer();
  ChunkStreamer(const ChunkStreamer&) = delete;
  ChunkStreamer& operator=(const ChunkStreamer&) = delete;

  struct Key {
    int32_t x = 0, y = 0;
    bool region = false;   // a region plan (rx, ry) instead of a chunk (cx, cy)
  };
  // the work wanted soon, most urgent first. Replaces the previous wish list; what is already ready is skipped.
  void want(const std::vector<Key>& keys);
  // a ready chunk, moved out (false: not ready; the caller generates it itself)
  bool takeChunk(int32_t cx, int32_t cy, ew::ChunkData& out);
  bool hasChunk(int32_t cx, int32_t cy);
  // a ready region plan (a copy made by the worker), nullptr if none. Valid until the next call into the streamer.
  const ew::RegionPlan* region(int32_t rx, int32_t ry);
  // M2 travel: the region plan is ready for the main thread (a worker's copy, or one the pump built into the main
  // source's cache)
  bool hasRegion(int32_t rx, int32_t ry);
  // M2 travel: nothing left on the wish list and nothing being made
  bool idle();
  // forget ready chunks outside [cx0, cx1) x [cy0, cy1) (global chunk coordinates) once more than `keep` are held
  void trim(int32_t cx0, int32_t cy0, int32_t cx1, int32_t cy1, size_t keep);
  // collect finished work (native) or generate within the budget (web / no worker). Returns the chunks made this call.
  int pump(double budgetMs);
  bool threaded() const;

  struct Stats {
    int chunksMade = 0, regionsMade = 0;   // generated by the streamer (worker or pump) so far
    int readyChunks = 0, readyRegions = 0, wished = 0;
    double workMs = 0, maxChunkMs = 0;     // generation time spent by the streamer
  };
  Stats stats();

 private:
  struct Impl;
  std::unique_ptr<Impl> d_;
};
