// M6b "Sagas": archetypes from ancient myth (Greek, Norse, Celtic, Mesopotamian, Persian, Indian, East Asian; close
// retellings allowed). ARCHETYPES lane. The template markup and role conventions: rpg/story/saga.h; twists: twists.cpp.
//
//   do_not_look     THE SINGER WHO WENT DOWN        (Orpheus) a widowed singer's beloved among the dead of a ruin; one rule
//   set_labours     THE LABOURS SET TO BREAK YOU    (Heracles) a penitent's three labours, set by a steward who wants him dead
//   long_way_home   THE LONG ROAD HOME              (the Odyssey) a lost lord found in comfort far away; suitors in the hall
//   stolen_fire     THE FIRE FROM THE MOUNTAIN      (Prometheus) a smith chained in a cave for teaching the forge-secret
//   twilight_doom   THE DOOM FORETOLD               (the twilight of the gods) a seer's foretold last battle with the world boss
//   trickster_bound THE TRICKSTER BOUND             (Loki) a beloved jester whose prank killed the town's darling
//   undying_herb    THE HERB OF UNDYING             (Gilgamesh) a proud lord, a dead friend, a herb at the bottom of a cave
//   guests_unknown  THE GUESTS NOBODY TOOK IN       (Baucis and Philemon) two ragged strangers turned from every door but one
#include <vector>
#include "rpg/story/arch/arch_tables.h"

namespace story {
namespace saga {
namespace arch {

namespace {

// ---------------------------------------------------------------- Orpheus
const char* const kDoNotLook = R"SAGA(
title [[THE SINGER WHO WENT DOWN|DO NOT LOOK BACK|THE SONG FOR THE DEAD]]
hook npc innkeeper
pitch "[[pitch=WHY DOES NOBODY SING HERE?|WHOSE LUTE IS THAT ON THE WALL?|IT'S VERY QUIET FOR AN INN.]]"
hint "[[~pitch|THE LUTE STAYS ON THE WALL. NOBODY TOUCHES IT. NOT EVEN ME.|THE LUTE STAYS ON THE WALL. NOBODY TOUCHES IT. NOT EVEN ME.|THERE USED TO BE SINGING IN HERE EVERY NIGHT. YOU SHOULD HAVE HEARD IT. YOU SHOULD HAVE HEARD HER.]]"
role giver giver
role home site home
role ruin ruin near
role lost person [[male|female]] at ruin
role keeper person [[male|female]] at ruin
var sang 0
slot t1 -> descend price mercy identity betrayal
slot t2 -> climb wonder prophecy return

stage start
  talk giver
  say "MY {LOST.HUSBAND} {LOST} DIED AT MIDSUMMER, OF A SNAKE IN THE LONG GRASS. ON THE DARK OF THE MOON THE DEAD OF {RUIN} WALK THEIR OLD HALLS, THEY SAY, AND A LIVING VOICE CAN CALL ONE BACK UP THE STAIR. I CAN'T SING. YOU CAN. <<plea:love>>"
  opt "I'LL GO DOWN FOR {LOST.HIM}." -> @t1
  opt "WHO TOLD YOU THAT?" -> who
  opt "LET THE DEAD REST." -> refused

stage who
  talk giver
  say "AN OLD SONG. EVERYONE KNOWS IT AND NOBODY BELIEVES IT. IT HAS A RULE IN THE LAST VERSE: THE ONE WHO LEADS MUST NOT LOOK BACK UNTIL BOTH ARE IN THE SUN. THE SONG NEVER SAYS IF ANYONE MANAGED IT. <<doubt>>"
  opt "THEN I'LL BE THE FIRST." -> @t1
  opt "IT'S ONLY A SONG." -> refused

stage refused
  end fail
  say "YES. ONLY A SONG. <<grief>>"
  journal "YOU WOULD NOT GO DOWN INTO {RUIN} FOR {GIVER}'S DEAD."
  do remember giver "I WENT TO {RUIN} MYSELF ON THE DARK OF THE MOON. I SAT AT THE TOP OF THE STAIRS ALL NIGHT. I DIDN'T GO DOWN. I COULDN'T."

stage descend
  goal kill 4 undead in ruin
  then gate
  journal "ON THE DARK OF THE MOON, GO DOWN INTO {RUIN}, WHERE THE DEAD WALK, AND CALL {LOST} BACK FOR {GIVER}."
  say "SING {LOST.HIM} THE ONE ABOUT THE [[song=SALT AND THE SWALLOW|MILLER'S DAUGHTER|LONG ROAD NORTH]]. {LOST.HE}'LL KNOW IT."

stage gate
  talk keeper
  say "A LIVING THING, ON THE STAIR OF {RUIN.OLD}. I WAS STEWARD HERE WHEN {RUIN.LORD} HELD IT, AND I KEEP IT STILL. YOU WANT ONE OF MINE. EVERYONE WHO COMES DOWN WANTS ONE OF MINE. SING, THEN. MOVE ME."
  opt "SING {LOST.HIS} SONG." -> sang
  opt "LET {LOST.HIM} GO. PLEASE." -> plead
  opt "STAND ASIDE OR FALL." -> force

stage sang
  talk keeper
  do set sang 1
  say "...THE [[=song]]. NOBODY HAS SUNG THAT HERE SINCE {RUIN.OLD} FELL. TAKE {LOST.HIM}. BUT HEAR THE RULE: {LOST.HE} WALKS BEHIND YOU. YOU DO NOT LOOK BACK, NOT ONCE, UNTIL YOU BOTH STAND IN THE SUN."
  opt "I WON'T LOOK BACK." -> @t2

stage plead
  talk keeper
  say "PLEASE. THEY ALL SAY PLEASE. ...VERY WELL, FOR THE PLEASE. YOU KNOW THE RULE. EVERYONE KNOWS THE RULE. NOBODY EVER KEEPS IT. <<warning>>"
  opt "I WILL." -> @t2

stage force
  talk keeper
  say "FALL? I FELL [[years=THREE HUNDRED|TWO HUNDRED|A HUNDRED]] YEARS AGO. YOU CANNOT THREATEN THE DEAD WITH WHAT THEY'VE ALREADY HAD. GO HOME, LIVING THING. <<threat>>"
  opt "THEN I'LL SING." -> sang
  opt "THEN I'LL GO HOME." -> empty_end

stage climb
  goal goto home
  then last_step
  do moves lost home
  journal "{LOST} WALKS BEHIND YOU OUT OF {RUIN}. YOU HEAR NO FOOTSTEPS. DO NOT LOOK BACK UNTIL YOU STAND IN THE SUN AT {HOME}."

stage last_step
  talk lost
  say "{PLAYER}? ARE YOU STILL THERE? I CAN'T HEAR YOU WALKING. I CAN'T HEAR MYSELF WALKING. IS IT REALLY YOU, OR IS THIS ANOTHER DREAM THEY GIVE US DOWN HERE? TURN ROUND. PLEASE. JUST SO I KNOW."
  opt "KEEP WALKING. IT'S ME." -> sun_end
  opt "TURN AND LOOK." -> looked_end

stage sun_end
  end success
  say "YOU STEPPED INTO THE SUN AT THE EDGE OF {HOME}, AND THEN YOU TURNED. {LOST} WAS THERE, SQUINTING, SHADOW AND ALL. {GIVER} DROPPED A WHOLE TRAY OF CUPS AND DID NOT NOTICE."
  journal "YOU LED {LOST} UP FROM THE DEAD OF {RUIN} WITHOUT LOOKING BACK. {GIVER} HAS {GIVER.HIS} {LOST.HUSBAND} AGAIN."
  do reward rich
  do remember giver "THE LUTE'S OFF THE WALL. {LOST} SINGS EVERY NIGHT. BADLY. I'VE NEVER HEARD ANYTHING SO BEAUTIFUL."
  do remember lost "I DON'T REMEMBER BELOW. ONLY YOUR BACK, GOING UP THE STAIRS AHEAD OF ME. I DREAM ABOUT YOUR BACK. IS THAT STRANGE?"
  do fact "{LOST} OF {HOME} DIED AT MIDSUMMER AND CAME BACK UP FROM {RUIN} ON THE DARK OF THE MOON. THE OLD SONG WAS TRUE."
  do mark led_one_up_from_the_dead

stage looked_end
  end fail
  say "YOU TURNED. {LOST} WAS THERE, ONE STEP BELOW THE SUNLIGHT, FOR AS LONG AS IT TAKES TO SAY A NAME. THEN THE STAIR WAS EMPTY, AND IT WAS VERY COLD."
  journal "YOU LOOKED BACK ON THE LAST STEP OF {RUIN}. {LOST} IS GONE BACK TO THE DEAD. YOU WILL HAVE TO TELL {GIVER}."
  do remember giver "YOU TURNED ROUND. I KNOW. ANYONE WOULD HAVE. I WOULD HAVE. IT DOESN'T HELP. IT HELPS A LITTLE."
  do fact "SOMEONE CALLED {LOST} UP FROM THE DEAD OF {RUIN}, AND LOOKED BACK ON THE LAST STEP, AS EVERYONE DOES IN THE SONG."
  do mark looked_back

stage empty_end
  end fail
  journal "THE KEEPER OF {RUIN} SENT YOU HOME EMPTY-HANDED. {LOST} STAYS AMONG THE DEAD."
  do remember giver "YOU WENT DOWN, AT LEAST. YOU WENT FURTHER THAN I DID. THANK YOU FOR THAT."
)SAGA";

// ---------------------------------------------------------------- Heracles
const char* const kSetLabours = R"SAGA(
title [[THE LABOURS SET TO BREAK YOU|THREE LABOURS FOR A PENITENT|THE STEWARD'S TASKS]]
hook npc guard
pitch "[[pitch=WHY IS THAT BIG MAN IN CHAINS?|WHO IS THE PRISONER?|WHAT DID HE DO?]]"
hint "[[~pitch|DON'T STAND TOO CLOSE TO THE BIG ONE. HE DOESN'T MEAN HARM. HE NEVER MEANT HARM. THAT'S THE TROUBLE.|HE ASKED TO BE CHAINED. ASKED! AND HE WEEPS AT NIGHT, AND SOMETIMES HE LAUGHS. I DON'T KNOW WHICH IS WORSE.|DON'T STAND TOO CLOSE TO THE BIG ONE. HE DOESN'T MEAN HARM. HE NEVER MEANT HARM. THAT'S THE TROUBLE.]]"
role giver giver
role home site home
role penitent person male at home
role steward person [[male|female]] at home
role ruin ruin near
role cave site cave near
var help 0
slot t1 -> second rival betrayal deceit price
slot t2 -> judged mercy prophecy wonder world

stage start
  talk giver
  say "{PENITENT}. STRONGEST MAN IN {HOME}. LAST WINTER A FIT CAME ON HIM, A MADNESS, AND WHEN IT LIFTED HIS OWN HOUSE WAS... HE'S ASKED FOR PENANCE. {STEWARD} HAS SET HIM THREE LABOURS. ANY ONE OF THEM WOULD KILL A REGIMENT. <<doubt>>"
  opt "WHAT ARE THE LABOURS?" -> labours
  opt "I'LL SPEAK WITH {PENITENT}." -> penitent_talk
  opt "A KILLER SHOULD HANG." -> refused

stage refused
  end fail
  say "MAYBE. {STEWARD} THINKS THE SAME, AND HAS FOUND A SLOWER ROPE. <<farewell>>"
  journal "YOU LEFT {PENITENT} TO {STEWARD}'S LABOURS."
  do remember giver "{PENITENT} WENT ALONE TO THE FIRST LABOUR. HE CAME BACK. HE WENT TO THE SECOND. WE'RE STILL WAITING."

stage labours
  talk giver
  say "CLEANSE THE BARROWS OF {RUIN}, WHERE THE DEAD WON'T LIE DOWN. BRING UP THE [[thing=GOLDEN FLEECE-HIDE|IRON APPLE|BRONZE BELL]] FROM THE BOTTOM OF {CAVE}. AND THE THIRD {STEWARD} WON'T NAME TILL THE SECOND IS DONE. FUNNY, THAT."
  opt "I'LL STAND WITH {PENITENT}." -> penitent_talk
  opt "THAT'S MURDER BY ERRAND." -> penitent_talk

stage penitent_talk
  talk penitent
  say "DON'T. DON'T BE KIND TO ME. I DON'T REMEMBER IT, YOU UNDERSTAND? THAT'S THE WORST. I WOKE AND THEY WERE... AND MY HANDS... IF THE LABOURS KILL ME, GOOD. IF THEY DON'T, I'VE PAID. EITHER WAY IT'S DONE."
  opt "THEN I'LL LABOUR BESIDE YOU." -> first
  opt "IT WASN'T YOU. IT WAS THE FIT." -> fit

stage fit
  talk penitent
  say "THE PRIESTS SAY A GOD SENT IT, OUT OF SPITE AT MY MOTHER. I'M SUPPOSED TO FEEL BETTER. A GOD'S SPITE, AND MY HANDS. <<grief:shame>>"
  opt "LET ME HELP YOU CARRY IT." -> first

stage first
  goal kill 5 undead in ruin
  then @t1
  journal "THE FIRST LABOUR: CLEANSE THE BARROWS OF {RUIN} OF THE DEAD THAT WALK THERE. {PENITENT} GOES WITH YOU."
  do set help 1

stage second
  goal fetch "THE [[=thing]]" in cave
  then third
  journal "THE SECOND LABOUR: BRING UP THE [[=thing]] FROM THE BOTTOM OF {CAVE}, {CAVE.DIR} OF {HOME}."

stage third
  talk steward
  say "BOTH? YOU HAD HELP. THE LAW SAYS HE MUST LABOUR ALONE, SO NEITHER COUNTS. ...WELL, LET'S BE GENEROUS. THE THIRD: HE GOES DOWN INTO {RUIN}'S DEEPEST VAULT, ALONE, AND BRINGS UP THE HOUND THAT GUARDS ITS DEAD."
  opt "YOU MEAN HIM TO DIE." -> @t2
  opt "THEN I'LL GO DOWN WITH HIM." -> @t2
  opt "HE'S DONE ENOUGH." check level 4 -> cowed else @t2

stage cowed
  talk steward
  say "...ENOUGH. PERHAPS. THE TOWN IS WATCHING YOU, AND THE TOWN LIKES HIM BETTER THAN ME. VERY WELL. THE LABOURS ARE ACCOMPLISHED. I'LL WRITE IT IN THE ROLL MYSELF. <<doubt>>"
  opt "WRITE IT CLEARLY." -> judged

stage judged
  talk penitent
  say "IT'S... IS IT DONE? THEY'RE SAYING IT'S DONE. I THOUGHT I'D FEEL CLEAN. I FEEL TIRED. ...{PLAYER}, WHAT DO I DO NOW? NOBODY TOLD ME WHAT YOU DO AFTER."
  opt "YOU LIVE. THAT'S THE HARD PART." -> live_end
  opt "YOU GO DOWN FOR THE HOUND." -> hound
  opt "YOU LEAVE {HOME} AND START AGAIN." -> leave_end

stage hound
  goal enter ruin
  then hound_end
  journal "THE LAST LABOUR: GO DOWN WITH {PENITENT} INTO THE DEEPEST VAULT OF {RUIN} AND BRING UP WHATEVER GUARDS ITS DEAD."

stage hound_end
  end success
  say "HE CAME UP FROM THE VAULT CARRYING A THREE-COLLARED HOUND THE SIZE OF A PONY, ASLEEP IN HIS ARMS LIKE A PUP. {STEWARD} LOCKED {STEWARD.HIS} DOOR AND DID NOT COME OUT FOR A WEEK."
  journal "{PENITENT} COMPLETED EVERY LABOUR {STEWARD} SET. THE HOUND OF {RUIN} SLEEPS AT HIS FEET IN {HOME} NOW."
  do reward rich
  do remember penitent "THE HOUND FOLLOWS ME EVERYWHERE. IT LIKES CHILDREN. I'M LEARNING TO, AGAIN. ONE AT A TIME."
  do fact "{PENITENT} OF {HOME} DID THE LABOURS SET TO BREAK HIM, AND CAME UP FROM {RUIN}'S VAULT WITH ITS HOUND ASLEEP IN HIS ARMS."
  do mark labours_done

stage live_end
  end success
  say "{PENITENT} STAYED IN {HOME}. HE MENDS ROOFS NOW, FOR NOTHING, AND NEVER SPEAKS OF THE WINTER. THE CHILDREN ARE AFRAID OF HIM, AND THEN ONE DAY THEY AREN'T."
  journal "THE LABOURS ARE DONE. {PENITENT} LIVES ON IN {HOME}, MENDING OTHER PEOPLE'S ROOFS."
  do reward fair
  do remember steward "THE ROLL SAYS ACCOMPLISHED. I WROTE IT MYSELF. I DON'T HAVE TO LIKE IT, AND I DON'T."
  do remember penitent "I MENDED THE TEMPLE ROOF TODAY. THE PRIEST BROUGHT ME BREAD. JUST HANDED IT ME. LIKE I WAS ANYONE."
  do fact "{PENITENT} OF {HOME} DID PENANCE FOR A MADNESS THAT WAS NOT HIS FAULT, AND MENDS ROOFS THERE FOR NOTHING."

stage leave_end
  end success
  say "{PENITENT} LEFT {HOME} AT DAWN WITH A STAFF AND NOTHING ELSE, AND DID NOT LOOK BACK. THEY SAY HE IS FIGHTING MONSTERS IN THE SOUTH, AND THAT HE NEVER SMILES."
  journal "THE LABOURS ARE DONE, AND {PENITENT} HAS LEFT {HOME} FOREVER. NOBODY KNOWS IF HE FOUND WHAT HE WAS LOOKING FOR."
  do reward fair
  do hide penitent
  do remember giver "HE LEFT. I THINK HE WAS AFRAID TO BE FORGIVEN. SOME PEOPLE ARE. THEY'D RATHER BE PUNISHED. IT'S SIMPLER."
)SAGA";

// ---------------------------------------------------------------- the Odyssey
const char* const kLongWayHome = R"SAGA(
title [[THE LONG ROAD HOME|TWENTY YEARS GONE|THE BOW ON THE WALL]]
hook npc any
pitch "[[pitch=WHO ARE THE LOUD ONES IN THE HALL?|WHOSE HOUSE IS SO NOISY?|WHY IS THE OLD DOG ON THE STEP?]]"
hint "[[~pitch|EVERY NIGHT THEY EAT OUR SHEEP AND DRINK OUR WINE AND ASK MY MOTHER WHICH OF THEM SHE'LL WED.|EVERY NIGHT THEY EAT OUR SHEEP AND DRINK OUR WINE AND ASK MY MOTHER WHICH OF THEM SHE'LL WED.|THE OLD DOG LIES ON THE STEP AND WATCHES THE ROAD. HE'S WATCHED IT TWENTY YEARS.]]"
role giver giver
role home site home
role far site town far
role wanderer person male at far
role foe foe male at home
role nurse person female at home
var told 0
slot t1 -> disguise wonder betrayal price world
slot t2 -> trial mercy rival identity deceit

stage start
  talk giver
  say "MY FATHER, {WANDERER}, WENT TO THE WAR WHEN I WAS IN THE CRADLE. [[twenty=TWENTY|NINETEEN|EIGHTEEN]] YEARS. NOW SUITORS FILL OUR HALL, EATING US BARE, AND {FOE} IS THE WORST OF THEM. A SAILOR SAYS {WANDERER} LIVES IN {FAR}, IN COMFORT. <<plea>>"
  opt "I'LL BRING HIM HOME." -> road
  opt "WHY HASN'T HE COME HOME?" -> why
  opt "TWENTY YEARS? LET HIM BE." -> refused

stage why
  talk giver
  say "THE SAILOR SAYS A RICH WIDOW KEEPS HIM, AND THE WINE IS GOOD, AND THE DAYS RUN TOGETHER. HE SAYS MY FATHER CRIES SOMETIMES AT SUNSET, LOOKING THIS WAY, AND DOESN'T KNOW WHY. <<grief>>"
  opt "THEN I'LL REMIND HIM WHY." -> road
  opt "HE'S CHOSEN COMFORT." -> refused

stage refused
  end fail
  say "COMFORT. YES. MY MOTHER CHOSE TO WAIT. WE ALL CHOOSE SOMETHING. <<farewell>>"
  journal "YOU WOULD NOT LOOK FOR {WANDERER}. THE SUITORS STILL FILL THE HALL IN {HOME}."
  do remember giver "THE SUITORS ARE STILL HERE. MOTHER STILL WEAVES, AND UNPICKS IT AT NIGHT. I'M RUNNING OUT OF SHEEP."

stage road
  goal goto far
  then found
  journal "{WANDERER} OF {HOME} WENT TO WAR [[=twenty]] YEARS AGO AND IS SAID TO LIVE IN EASE IN {FAR}. SUITORS EAT HIS HALL BARE. FIND HIM."

stage found
  talk wanderer
  say "{HOME}? I KNOW THAT NAME... A ROCKY PLACE, GOATS ON THE HILLSIDE, A HOUSE WITH AN OLIVE TREE GROWING UP THROUGH THE BED. WHY DO I KNOW THAT? WHY DO MY EYES STING?"
  opt "YOUR CHILD. THE SUITORS. COME HOME." -> told
  opt "YOUR WIFE STILL WAITS." -> told
  opt "STAY. YOU'RE HAPPY HERE." -> comfort_end

stage told
  talk wanderer
  say "...THE OLIVE TREE. I BUILT THE BED AROUND IT WITH MY OWN HANDS. NOBODY ELSE KNOWS THAT BUT HER. GODS. [[=twenty]] YEARS. I'LL COME. BUT NOT AS MYSELF. AS A BEGGAR. I WANT TO SEE WHO IS TRUE IN MY HOUSE BEFORE THEY SEE ME."
  do set told 1
  opt "AS A BEGGAR, THEN." -> @t1

stage disguise
  goal goto home
  then nurse_talk
  do moves wanderer home
  journal "{WANDERER} WALKS HOME TO {HOME} IN A BEGGAR'S RAGS. THE OLD DOG ON THE STEP LIFTED ITS HEAD, AND WAGGED ONCE, AND DIED HAPPY."

stage nurse_talk
  talk nurse
  say "I WAS WASHING THE BEGGAR'S FEET, AS IS PROPER, AND I FOUND THE SCAR. THE BOAR'S TUSK, ABOVE THE KNEE. I NURSED THAT SCAR. HE PUT HIS HAND OVER MY MOUTH. ...WHAT HAPPENS NOW? THE SUITORS ARE AT THE TABLE."
  opt "NOW THE BOW COMES DOWN." -> @t2

stage trial
  talk wanderer
  say "SHE'S SET A TEST: WHOEVER CAN STRING MY OLD BOW AND SHOOT THROUGH TWELVE AXE-HEADS, SHE'LL WED. {FOE} AND THE REST HAVE ALL FAILED. THEY'RE LAUGHING. THEY'LL LET A BEGGAR TRY, FOR THE JOKE. AND THEN, {PLAYER}?"
  opt "THEN THEY ANSWER FOR IT." -> slaughter
  opt "THEN THEY LEAVE. ALIVE." -> drive
  opt "THEN SHE KNOWS YOU. ONLY THAT." -> bed

stage slaughter
  goal slay foe
  then blood_end
  journal "THE BEGGAR STRUNG THE BOW. {FOE}, CHIEF OF THE SUITORS IN {WANDERER}'S HALL, IS THE FIRST TO DRAW A KNIFE."

stage drive
  talk wanderer
  say "I STRUNG IT, AND THE HALL WENT QUIET, AND {FOE} LOOKED AT MY HANDS AND KNEW THEM. THEY'RE GOING. ALL OF THEM, DOWN THE HILL, WITHOUT THEIR CLOAKS. NOBODY HAD TO DIE. I'D FORGOTTEN THAT WAS POSSIBLE."
  opt "AND NEVER COME BACK." -> drive_end

stage bed
  talk nurse
  say "SHE TESTED HIM. SHE TOLD ME, IN FRONT OF HIM, TO MOVE THE GREAT BED OUT INTO THE HALL FOR THE GUEST. AND HE WENT WHITE, AND SAID NOBODY CAN MOVE THAT BED, IT HAS AN OLIVE TREE FOR A POST. AND SHE RAN TO HIM."
  opt "AND THE SUITORS?" -> drive

stage blood_end
  end success
  say "THE HALL IS SCRUBBED NOW, AND SCRUBBED AGAIN. THERE ARE STILL MARKS ON THE FLOOR. {WANDERER} SITS IN HIS CHAIR WITH HIS WIFE'S HAND IN HIS, AND THE TOWN IS VERY CAREFUL AROUND HIM."
  journal "{WANDERER} IS HOME IN {HOME} AFTER [[=twenty]] YEARS. THE SUITORS DID NOT LEAVE HIS HALL ALIVE."
  do reward fair
  do remember giver "MY FATHER IS HOME. HE LAUGHS LIKE A STORM COMING IN. BUT I DON'T GO INTO THE HALL AFTER DARK. NOT YET."
  do fact "{WANDERER} OF {HOME} CAME HOME FROM THE WAR AFTER [[=twenty]] YEARS DRESSED AS A BEGGAR, AND STRUNG HIS OLD BOW, AND THE SUITORS DIED IN HIS HALL."

stage drive_end
  end success
  say "THE SUITORS RAN DOWN THE HILL SO FAST ONE OF THEM LOST A BOOT. {WANDERER} SAT DOWN ON THE STEP BESIDE THE OLD DOG'S EMPTY PLACE AND WEPT, AND HIS WIFE SAT WITH HIM."
  ?m_hope journal "{WANDERER} IS HOME IN {HOME} AFTER [[=twenty]] YEARS, AND THE SUITORS ARE GONE. THE WAITING WAS NOT FOR NOTHING."
  !m_hope journal "{WANDERER} IS HOME IN {HOME} AFTER [[=twenty]] YEARS. THE SUITORS FLED, AND NOBODY DIED."
  do reward rich
  do remember giver "FATHER TAUGHT ME TO STRING THE BOW TODAY. I CAN'T. NOT YET. HE SAYS HE COULDN'T EITHER, AT MY AGE. I THINK HE'S LYING. I LOVE HIM."
  do remember wanderer "THE OLIVE TREE STILL HOLDS UP THE BED. TWENTY YEARS. IT NEVER EVEN NOTICED I WAS GONE."
  do fact "{WANDERER} OF {HOME} CAME HOME FROM THE WAR AFTER [[=twenty]] YEARS, STRUNG HIS OLD BOW, AND SENT THE SUITORS RUNNING WITHOUT A DROP OF BLOOD."
  do mark long_road_home

stage comfort_end
  end fail
  say "{WANDERER} SMILED, AND POURED YOU MORE WINE, AND LOOKED WEST AT THE SUNSET AND RUBBED HIS EYES AND DIDN'T KNOW WHY."
  journal "YOU LEFT {WANDERER} IN COMFORT IN {FAR}. THE SUITORS STILL FILL HIS HALL IN {HOME}."
  do remember wanderer "STRANGE. YOU MENTIONED SOMEWHERE. A ROCKY PLACE. I DREAM OF IT NOW. I WISH YOU HADN'T COME."
)SAGA";

// ---------------------------------------------------------------- Prometheus
const char* const kStolenFire = R"SAGA(
title [[THE FIRE FROM THE MOUNTAIN|THE CHAINED SMITH|WHAT THE TEMPLE KEPT]]
hook npc smith
pitch "[[pitch=THAT'S A STRANGE COLOUR OF FLAME.|HOW DO YOU GET YOUR FIRE SO HOT?|WHERE DID YOU LEARN THAT TEMPER?]]"
hint "[[~pitch|DON'T ASK WHERE THE BLUE FIRE CAME FROM. THE PRIESTS GET NERVOUS.|EVERY SMITH IN THIS TOWN WORKS HOTTER THAN THE CITY TEMPLES NOW. THERE'S A REASON, AND A PRICE.|EVERY SMITH IN THIS TOWN WORKS HOTTER THAN THE CITY TEMPLES NOW. THERE'S A REASON, AND A PRICE.]]"
role giver giver
role home site home
role cave site cave near
role titan person [[male|female]] at cave
role priest npc priest at home
var learned 0
slot t1 -> go price betrayal deceit rival
slot t2 -> verdict mercy wonder prophecy world

stage start
  talk giver
  say "MY MASTER, {TITAN}, WAS A TEMPLE SMITH. THE PRIESTS KEPT THE SECRET OF THE BLUE FIRE FOR THE GOD'S OWN BLADES. {TITAN} CARRIED A COAL OF IT DOWN THE MOUNTAIN IN A FENNEL STALK AND TAUGHT IT TO EVERY FORGE IN {HOME}. <<boast:pride>>"
  opt "AND WHAT DID IT COST?" -> cost
  opt "THE TEMPLE'S SECRET WAS STOLEN." -> stolen
  opt "A SMITHS' QUARREL. NOT MINE." -> refused

stage refused
  end fail
  say "NO. SMITHS' QUARRELS ARE NEVER ANYBODY'S, UNTIL THE PLOUGHS BREAK. <<farewell>>"
  journal "YOU WOULD NOT GO TO {TITAN} IN {CAVE}."
  do remember giver "THE BLUE FIRE STILL BURNS IN MY FORGE. {TITAN} IS STILL IN THE CAVE. I LIGHT IT EVERY MORNING AND I THINK OF {TITAN.HIM}."

stage cost
  talk giver
  say "THEY CHAINED {TITAN} TO THE ROCK IN {CAVE}. EVERY DAY THE CARRION BIRDS COME. THE PRIESTS SAY THE GOD SENDS THEM. I THINK THE PRIESTS FEED THEM. <<curse>>"
  opt "THEN I'LL BREAK THE CHAIN." -> @t1
  opt "LET ME HEAR THE PRIEST." -> stolen

stage stolen
  talk priest
  say "STOLEN, YES. THAT FIRE WAS NEVER MEANT FOR PLOUGHSHARES. NOW EVERY HOTHEAD IN {HOME} CAN FORGE A BLADE THAT CUTS MAIL. {TITAN} GAVE CHILDREN KNIVES AND CALLED IT KINDNESS. <<warning>>"
  opt "AND PLOUGHS THAT DON'T BREAK." -> @t1
  opt "PERHAPS YOU'RE RIGHT." -> @t1

stage go
  goal enter cave
  then chained
  journal "{TITAN}, THE SMITH WHO BROUGHT THE TEMPLE'S BLUE FIRE TO {HOME}, IS CHAINED TO THE ROCK IN {CAVE}, {CAVE.DIR}."

stage chained
  talk titan
  say "YOU CAME. THE BIRDS ARE LATE TODAY. ...I'D DO IT AGAIN. A FARMER'S CHILD IN {HOME} HAS A PLOUGH THAT WON'T CRACK ON THE FIRST STONE. FOR THAT? THE BIRDS ARE CHEAP. WHAT ARE YOU HERE FOR, {PLAYER}?"
  opt "TO BREAK YOUR CHAINS." -> birds
  opt "TO LEARN THE FIRE MYSELF." -> teach
  opt "TO TELL YOU TO REPENT." -> repent

stage teach
  talk titan
  say "OF COURSE. EVERYONE WHO COMES DOWN HERE WANTS IT. LISTEN: IT'S NOT THE COAL. IT'S THE BELLOWS. THREE SHORT, ONE LONG, LIKE A HEART. ...THERE. NOW YOU'RE AS GUILTY AS I AM. <<proverb>>"
  do set learned 1
  opt "NOW I'LL BREAK THE CHAINS." -> birds
  opt "THANK YOU. I MUST GO." -> @t2

stage repent
  talk titan
  say "REPENT. FOR WARM HOUSES AND STRONG PLOUGHS. ...GO HOME, PRIEST'S ERRAND-RUNNER. TELL THEM THE BIRDS ARE STILL HUNGRY. <<insult>>"
  opt "I'LL BREAK THE CHAINS ANYWAY." -> birds
  opt "SO BE IT." -> @t2

stage birds
  goal kill 4 beast in cave
  then freed
  journal "THE CARRION THINGS OF {CAVE} HAVE COME TO FEED ON {TITAN}. DRIVE THEM OFF, THEN BREAK THE CHAIN."

stage freed
  talk titan
  say "THE CHAIN. YOU BROKE IT WITH A HAMMER FORGED IN BLUE FIRE. DO YOU SEE? THAT'S THE WHOLE ARGUMENT, RIGHT THERE IN YOUR HAND. <<thanks>>"
  opt "COME HOME TO {HOME}." -> @t2

stage verdict
  talk priest
  ?t2 say "SO. THE CHAIN IS BROKEN, OR IT ISN'T, AND THE FIRE IS LOOSE IN THE WORLD EITHER WAY. THE TEMPLE WANTS TO KNOW WHERE YOU STAND. CHOOSE CAREFULLY. WE HAVE LONG MEMORIES."
  !t2 say "SO. THE FIRE IS LOOSE IN THE WORLD, AND THE TEMPLE WANTS TO KNOW WHERE YOU STAND, STRANGER. CHOOSE CAREFULLY. THE GOD HAS A LONG MEMORY, AND SO DO HIS PRIESTS."
  opt "WITH {TITAN}. THE FIRE IS FOR ALL." -> fire_end
  opt "THE FIRE GOES BACK TO THE TEMPLE." -> temple_end
  opt "I'LL TEACH IT TO ONE SMITH ONLY." if var learned 1 -> one_end

stage fire_end
  end success
  say "{TITAN} CAME DOWN TO {HOME} THIN AS A RAKE, SCARRED WHERE THE BIRDS HAD BEEN, AND THE SMITHS LIT THEIR FORGES ALL AT ONCE SO THE WHOLE STREET GLOWED BLUE. THE TEMPLE BELL DID NOT RING THAT NIGHT."
  journal "{TITAN} IS FREE, AND THE BLUE FIRE BURNS IN EVERY FORGE OF {HOME}. THE TEMPLE HAS NOT FORGIVEN EITHER OF YOU."
  do reward fair
  do secret home
  do remember giver "{TITAN} IS AT MY FORGE EVERY MORNING, TEACHING THE APPRENTICES. THE PRIESTS WATCH FROM ACROSS THE STREET. LET THEM."
  do fact "THE SMITHS OF {HOME} WORK THE TEMPLE'S BLUE FIRE, BROUGHT DOWN THE MOUNTAIN BY {TITAN}, WHO WAS CHAINED FOR IT AND FREED."
  do mark fire_for_all

stage temple_end
  end success
  say "THE TEMPLE SENT MEN TO DOUSE THE FORGES OF {HOME}. THE PLOUGHS CRACK ON THE FIRST STONE AGAIN. THE PRIESTS ARE VERY GRATEFUL, AND PAID YOU FROM THE OFFERING BOX, AND DID NOT MEET YOUR EYES."
  journal "THE BLUE FIRE IS THE TEMPLE'S AGAIN. THE FORGES OF {HOME} BURN ORANGE AND COOL, AND {GIVER} WILL NOT SPEAK TO YOU."
  do reward fair
  do remember giver "MY FORGE BURNS ORANGE. THE PLOUGH I MADE TODAY WILL CRACK BY HARVEST. GET OUT OF MY SMITHY."
  do fact "THE TEMPLE TOOK BACK ITS BLUE FIRE FROM THE FORGES OF {HOME}. THE PLOUGHS THERE CRACK AGAIN."

stage one_end
  end success
  say "YOU TAUGHT THE BELLOWS-BEAT TO {GIVER} ALONE, AT NIGHT, WITH THE SHUTTERS CLOSED. THE TEMPLE SUSPECTS. {GIVER}'S PLOUGHS DO NOT CRACK. ONE FORGE BURNS BLUE IN {HOME}, AND IT IS ENOUGH TO START WITH."
  journal "ONE FORGE IN {HOME} BURNS WITH THE BLUE FIRE. THE SECRET IS SAFE WITH {GIVER}, FOR NOW."
  do reward fair
  do secret home
  do remember giver "THREE SHORT, ONE LONG. LIKE A HEART. I SAY IT UNDER MY BREATH WHEN THE PRIESTS GO BY."
)SAGA";

// ---------------------------------------------------------------- the twilight of the gods
const char* const kTwilightDoom = R"SAGA(
title [[THE DOOM FORETOLD|THE LAST WINTER|WHEN THE HORN SOUNDS]]
hook npc priest
pitch "[[pitch=WHY ARE YOU COUNTING THE WINTERS?|WHAT DID THE BONES SAY?|WHY IS THE TEMPLE FIRE OUT?]]"
hint "[[~pitch|THREE WINTERS WITH NO SUMMER BETWEEN. THE OLD BOOKS HAVE A WORD FOR THAT. I WON'T SAY IT.|I CAST THE BONES THREE TIMES. THEY SAID THE SAME THING THREE TIMES. I PUT THE FIRE OUT.|I CAST THE BONES THREE TIMES. THEY SAID THE SAME THING THREE TIMES. I PUT THE FIRE OUT.]]"
role giver giver
role home site home
role foe boss
role far site town near
role young person [[male|female]] at home
role old person [[male|female]] at home
var stayed 0
slot t1 -> mustering rival betrayal prophecy price
slot t2 -> eve wonder world return mercy identity

stage start
  talk giver
  say "<<omen>> THE BONES SAY {FOE}, THE {FOE.KIND}, WILL COME DOWN ON {HOME} WHEN THE THIRD WINTER BREAKS. THE OLD SONGS SAY THE SAME: THE LAST BATTLE, AND EVERY HERO IN IT FALLS. AND AFTER, A GREEN WORLD, FOR THOSE WHO LIVE TO SEE IT."
  opt "THEN WE FIGHT IT." -> fight_talk
  opt "THEN GET THE CHILDREN OUT." -> children
  opt "BONES SAY WHAT YOU WANT." -> refused

stage refused
  end fail
  say "I WISH THAT WERE TRUE. I'VE NEVER WANTED THIS. <<farewell>>"
  journal "YOU DID NOT BELIEVE {GIVER}'S BONES. {HOME} WAITS FOR THE THIRD WINTER TO BREAK."
  do remember giver "THE THIRD WINTER IS BREAKING. I SLEEP IN MY BOOTS. MAYBE YOU WERE RIGHT. MAYBE."

stage fight_talk
  talk old
  say "FIGHT IT? I'LL FIGHT. I'M [[age=SEVENTY|EIGHTY|SIXTY-FIVE]] AND I'VE BURIED EVERYONE I EVER LOVED, AND I'D LIKE TO DIE WITH AN AXE IN MY HAND AND NOT A SPOON. BUT THE CHILDREN, {PLAYER}. THE SONG SAYS THE WORLD AFTER IS GREEN. SOMEONE HAS TO SEE IT."
  opt "THEN THE CHILDREN GO FIRST." -> children
  opt "NOBODY GOES. WE STAND." -> @t1

stage children
  talk young
  say "TO {FAR}? WITHOUT MY [[MOTHER|GRANDMOTHER]]? ...SHE SAYS I HAVE TO. SHE SAYS SOMEBODY HAS TO REMEMBER THE SONGS AFTER. I DON'T WANT TO REMEMBER THE SONGS. I WANT HER."
  opt "I'LL TAKE YOU THERE MYSELF." -> exodus
  opt "THEN STAY. WE'LL STAND TOGETHER." -> @t1

stage exodus
  goal goto far
  then @t1
  do moves young far
  do set stayed 1
  journal "THE CHILDREN OF {HOME} GO TO {FAR}, AWAY FROM THE FORETOLD DOOM. LEAD THEM THERE, THEN COME BACK FOR THE LAST BATTLE."

stage mustering
  talk giver
  say "[[spears=FORTY|THIRTY|FIFTY]] SPEARS, AND {OLD} AT THE FRONT IN A HELM THAT DOESN'T FIT. THE WINTER IS BREAKING; YOU CAN HEAR THE ICE ON THE RIVER. {PLAYER}, IF THE BONES ARE RIGHT, WE ALL DIE TONIGHT. DO YOU STAND WITH US?"
  opt "I STAND." -> @t2
  opt "THE BONES CAN BE WRONG." -> @t2

stage eve
  talk old
  say "IT'S COMING. THE GROUND IS SHAKING. ...{PLAYER}. I WAS AFRAID MY WHOLE LIFE. OF WINTER, OF HUNGER, OF THE DARK. I'M NOT AFRAID NOW. ISN'T THAT STRANGE? <<oath>>"
  opt "THEN WE MEET IT HEAD-ON." -> battle
  opt "RUN. I'LL HOLD IT." -> alone

stage battle
  goal slay foe
  then dawn_end
  journal "{FOE}, THE {FOE.KIND} OF THE FORETOLD DOOM, COMES DOWN ON {HOME} AS THE THIRD WINTER BREAKS. MEET IT."

stage alone
  goal slay foe
  then alone_end
  journal "YOU SENT {HOME}'S LAST SPEARS AWAY. ONLY YOU STAND BETWEEN {FOE}, THE {FOE.KIND}, AND THE TOWN."

stage dawn_end
  end success
  say "THE BONES WERE WRONG ABOUT ONE THING. NOT EVERY HERO FELL. {OLD} DID, AXE IN HAND, LAUGHING. THE MORNING AFTER, THE FIRST GREEN SHOOTS IN THREE YEARS CAME UP THROUGH THE ASH."
  ?m_hope journal "THE FORETOLD DOOM CAME TO {HOME}, AND WAS MET, AND PASSED. {OLD} FELL. THE SPRING HAS COME AT LAST."
  !m_hope journal "THE FORETOLD DOOM CAME TO {HOME}. {FOE} FELL, AND SO DID {OLD}. AND THEN THE SPRING CAME."
  do reward great
  do remember giver "I'VE LIT THE TEMPLE FIRE AGAIN. I'VE THROWN AWAY THE BONES. THEY WERE RIGHT ABOUT THE BATTLE AND WRONG ABOUT THE END. I PREFER NOT KNOWING."
  do fact "{FOE}, THE {FOE.KIND} OF THE FORETOLD DOOM, CAME DOWN ON {HOME} AS THE THIRD WINTER BROKE. {HOME} MET IT, AND THE SPRING CAME."
  do mark doom_met

stage alone_end
  end success
  say "THEY CAME BACK AT DAWN, THE SPEARS, EXPECTING ASH. THEY FOUND YOU SITTING ON {FOE}'S CARCASS IN THE SNOWMELT. {OLD} WAS FURIOUS TO HAVE MISSED IT, AND LIVED TEN MORE YEARS TO COMPLAIN."
  journal "YOU MET THE FORETOLD DOOM ALONE, AND LIVED. {HOME}'S SPEARS ALL CAME HOME. THE BONES WERE WRONG."
  do reward great
  do fame 2
  do remember old "I MISSED IT! [[=age]] YEARS OF WAITING FOR A GOOD DEATH AND YOU STOLE IT. I'LL NEVER FORGIVE YOU. HAVE A DRINK."
  do fact "THE BONES FORETOLD THAT {HOME} WOULD FALL TO {FOE}, THE {FOE.KIND}. A STRANGER MET IT ALONE BY NIGHT, AND THE BONES WERE WRONG."
)SAGA";

// ---------------------------------------------------------------- Loki
const char* const kTricksterBound = R"SAGA(
title [[THE TRICKSTER BOUND|THE JESTER IN THE CAVE|THE BOWL AND THE VENOM]]
hook npc any
pitch "[[pitch=WHY IS NOBODY LAUGHING TODAY?|WHO DID THE TOWN BURY?|WHY IS THE FESTIVAL CANCELLED?]]"
hint "[[~pitch|THIS TOWN BURIED ITS BRIGHTEST CHILD THIS MONTH. AND ITS FUNNIEST MAN IS CHAINED IN A CAVE FOR IT.|NOBODY HAS TOLD A JOKE IN THIS TOWN SINCE THE FUNERAL. NOBODY DARES.|THIS TOWN BURIED ITS BRIGHTEST CHILD THIS MONTH. AND ITS FUNNIEST MAN IS CHAINED IN A CAVE FOR IT.]]"
role giver giver
role home site home
role cave site cave near
role jester person male at cave
role blind resident any
role wife person female at cave
var truth 0
slot t1 -> go betrayal deceit price rival
slot t2 -> bowl mercy wonder prophecy

stage start
  talk giver
  say "{JESTER} WAS OUR JOKER. THEN {HOME}'S BRIGHTEST, A YOUNG ONE EVERYONE LOVED, DIED AT THE SPRING GAMES. A DART OF MISTLETOE WOOD, THROWN BY {BLIND}, WHO IS BLIND, AND WHOSE HAND {JESTER} GUIDED. FOR A JOKE, HE SAID. <<grief>>"
  opt "WHERE IS {JESTER} NOW?" -> where
  opt "I'LL SPEAK TO {BLIND}." -> blind_talk
  opt "THEN HE EARNED HIS CHAINS." -> refused

stage refused
  end fail
  say "THAT'S WHAT EVERYONE SAYS. I SAY IT TOO, IN THE DAYTIME. <<farewell>>"
  journal "YOU LEFT {JESTER} CHAINED IN {CAVE}."
  do remember giver "{JESTER}'S STILL IN THE CAVE. HIS WIFE TOO, WITH THE BOWL. I DON'T KNOW WHICH OF THEM I PITY MORE."

stage where
  talk giver
  say "THE ELDERS CHAINED HIM IN {CAVE} OVER A STONE THAT DRIPS. A SNAKE'S VENOM, THEY SAY, BUT IT'S ONLY SOMETHING BITTER FROM THE ROCK. HIS WIFE {WIFE} HOLDS A BOWL OVER HIS FACE, DAY AND NIGHT. WHEN SHE EMPTIES IT, HE SCREAMS."
  opt "I'LL GO TO THE CAVE." -> @t1
  opt "FIRST I'LL SPEAK TO {BLIND}." -> blind_talk

stage blind_talk
  talk blind
  say "HE SAID IT WAS A GAME. EVERYONE WAS THROWING THINGS AT THE BRIGHT ONE, BECAUSE NOTHING COULD HURT [[THEM|HIM|HER]]. HE PUT A DART IN MY HAND AND TURNED MY SHOULDER. I HEARD EVERYONE STOP BREATHING. I DIDN'T KNOW. I DIDN'T KNOW."
  do set truth 1
  opt "IT WASN'T YOUR FAULT." -> @t1
  opt "WHY MISTLETOE?" -> mistletoe

stage mistletoe
  talk blind
  say "THE MOTHER MADE EVERY THING IN THE WORLD SWEAR NOT TO HARM HER CHILD: STONE, STEEL, FIRE, WATER. EVERYTHING BUT MISTLETOE. TOO YOUNG TO SWEAR, SHE SAID. {JESTER} ASKED HER WHAT SHE'D LEFT OUT, AS A JOKE. AND SHE TOLD HIM. <<grief>>"
  opt "I'LL GO TO {JESTER}." -> @t1

stage go
  goal enter cave
  then cave_mouth
  journal "{JESTER}, THE JOKER OF {HOME}, LIES CHAINED IN {CAVE} UNDER A DRIPPING STONE, AND {WIFE} HOLDS A BOWL OVER HIM."

stage cave_mouth
  talk wife
  say "DON'T COME CLOSER. THE BOWL IS NEARLY FULL. ...YOU WANT TO KNOW IF I FORGIVE HIM? I DON'T. I HOLD THE BOWL BECAUSE I LOVE HIM, AND THE TWO THINGS HAVE NOTHING TO DO WITH EACH OTHER. THEY NEVER DID."
  opt "LET ME HOLD THE BOWL A WHILE." -> @t2
  opt "I'LL TALK TO HIM." -> @t2

stage bowl
  talk jester
  say "A VISITOR! FORGIVE ME IF I DON'T GET UP. ...IT WAS A JOKE, AND THEN IT WASN'T, AND I WATCHED THE WHOLE TOWN'S FACE CHANGE AT ONCE. I'VE NEVER MADE A JOKE THAT GOOD. I'LL NEVER MAKE ANOTHER. <<apology>>"
  opt "I'LL BREAK THE CHAIN." -> freed_end
  opt "I'LL TAKE {WIFE}'S PLACE A NIGHT." -> bowl_end
  opt "YOU'LL STAY. FOR THE CHILD." -> bound_end

stage freed_end
  end success
  say "THE CHAIN PARTED. {JESTER} STOOD, AND LAUGHED, A SHORT, UGLY SOUND, AND WALKED OUT OF THE CAVE WITHOUT LOOKING AT EITHER OF YOU. {WIFE} STOOD THERE WITH THE BOWL IN HER HANDS FOR A LONG TIME."
  journal "YOU FREED {JESTER} FROM {CAVE}. HE HAS GONE, NOBODY KNOWS WHERE. THE OLD ONES SAY THE CHAIN WAS THERE FOR A REASON."
  do reward fair
  do remember wife "HE WENT. HE DIDN'T EVEN SAY GOODBYE. I KNEW HE WOULDN'T. I KEPT THE BOWL. I DON'T KNOW WHY."
  do fact "{JESTER}, WHO TRICKED A BLIND HAND INTO KILLING {HOME}'S BRIGHTEST CHILD, WAS FREED FROM {CAVE}. THE OLD ONES SAY HE'LL BE BACK AT THE END."
  do mark trickster_unbound

stage bowl_end
  end success
  say "YOU HELD THE BOWL THROUGH ONE LONG NIGHT, AND {WIFE} SLEPT FOR THE FIRST TIME IN A MONTH, CURLED ON THE STONE LIKE A CHILD. {JESTER} TOLD YOU JOKES ALL NIGHT. NONE OF THEM WERE FUNNY. ALL OF THEM WERE SAD."
  journal "{JESTER} STAYS BOUND IN {CAVE}. YOU HELD THE BOWL A NIGHT, SO {WIFE} COULD SLEEP. IT CHANGED NOTHING. IT CHANGED SOMETHING."
  do reward small
  do remember wife "YOU HELD THE BOWL. NOBODY ELSE EVER HAS. I SLEPT. I DREAMED OF NOTHING. IT WAS WONDERFUL."
  ?tw_fox_eyes do fact "A STRANGER HELD THE BOWL OVER {JESTER} FOR ONE NIGHT IN {CAVE}. THE FOX-EYED WOMAN AT THE WELL SAYS SHE SAW IT IN A DREAM."
  !tw_fox_eyes do fact "A STRANGER HELD THE BOWL OVER {JESTER} FOR ONE NIGHT IN {CAVE}, SO HIS WIFE COULD SLEEP."
  do mark held_the_bowl

stage bound_end
  end success
  say "{JESTER} DIDN'T ARGUE. HE JUST CLOSED HIS EYES AND SAID: TELL {BLIND} IT WAS MY HAND, NOT THEIRS. TELL THEM EVERY DAY UNTIL THEY BELIEVE IT. THE BOWL WAS FULL. {WIFE} TURNED TO EMPTY IT."
  journal "{JESTER} STAYS BOUND IN {CAVE} FOR THE DEATH OF {HOME}'S BRIGHTEST CHILD. HE ASKED YOU TO TELL {BLIND} THE FAULT WAS HIS."
  do reward fair
  do remember blind "YOU TOLD ME IT WAS HIS HAND. YOU TOLD ME AGAIN. I'M STARTING TO HEAR IT. THANK YOU FOR TELLING ME AGAIN."
  do fact "{JESTER} LIES BOUND IN {CAVE} FOR THE BRIGHT CHILD'S DEATH. HE SAYS THE FAULT WAS HIS ALONE, NOT THE BLIND HAND HE GUIDED."
)SAGA";

// ---------------------------------------------------------------- Gilgamesh
const char* const kUndyingHerb = R"SAGA(
title [[THE HERB OF UNDYING|THE LORD WHO WOULD NOT MOURN|THE THORN AT THE BOTTOM OF THE WATER]]
hook npc guard
pitch "[[pitch=WHY IS YOUR LORD UNSHAVEN?|WHY IS THE HALL DRAPED IN BLACK?|WHO DIED?]]"
hint "[[~pitch|THE LORD'S BROTHER-IN-ARMS IS DEAD. THE LORD WON'T BELIEVE IT. THE SMELL BELIEVES IT.|OUR LORD HASN'T WASHED OR SHAVED IN A MONTH. HE SITS BY HIS FRIEND'S BIER AND WON'T LET THEM BURY HIM.|OUR LORD HASN'T WASHED OR SHAVED IN A MONTH. HE SITS BY HIS FRIEND'S BIER AND WON'T LET THEM BURY HIM.]]"
role giver giver
role home site home
role lord person male at home
role friend person male at home
role cave site cave near
role old resident any
var gave 0
slot t1 -> bottom price wonder betrayal rival
slot t2 -> serpent world mercy prophecy deceit

stage start
  talk giver
  say "{LORD} AND {FRIEND} WERE TWO HANDS OF ONE MAN. THEY KILLED THE [[thing=BULL|BOAR|GIANT]] OF THE HILLS TOGETHER, WHEN THEY WERE YOUNG. NOW {FRIEND} IS DEAD OF A FEVER, AND {LORD} SITS BY THE BIER AND SAYS THERE'S A HERB THAT UNDOES DEATH. <<plea:fear>>"
  opt "I'LL SPEAK WITH {LORD}." -> lord_talk
  opt "IS THERE SUCH A HERB?" -> herb
  opt "GRIEF ISN'T MY BUSINESS." -> refused

stage refused
  end fail
  say "IT'S EVERYONE'S BUSINESS, SOONER OR LATER. <<farewell>>"
  journal "YOU LEFT {LORD} TO HIS GRIEF BY {FRIEND}'S BIER."
  do remember giver "THEY BURIED {FRIEND} AT LAST. {LORD} WASN'T THERE. HE'S GONE LOOKING FOR THE HERB HIMSELF."

stage herb
  talk old
  say "THE THORN-HERB? MY GRANDMOTHER SAID IT GROWS AT THE BOTTOM OF THE BLACK WATER IN {CAVE}. EAT IT AND YOU'RE YOUNG AGAIN. SHE ALSO SAID THE MOON WAS A CHEESE. <<doubt>>"
  opt "THEN I'LL DIVE FOR IT." -> lord_talk
  opt "AND THE LORD?" -> lord_talk

stage lord_talk
  talk lord
  say "SIX DAYS I SAT BY HIM, AND ON THE SEVENTH A WORM FELL FROM HIS NOSE. I AM AFRAID, {PLAYER}. I, WHO KILLED THE [[=thing]]. I AM AFRAID OF THE WORM. BRING ME THE HERB FROM {CAVE}. I'LL GIVE YOU ANYTHING."
  opt "I'LL BRING IT." -> dive
  opt "BURY YOUR FRIEND FIRST." -> bury

stage bury
  talk lord
  say "BURY HIM? AND ADMIT IT? ...YOU'RE RIGHT. HE'D LAUGH AT ME, SITTING HERE STINKING. HE ALWAYS LAUGHED AT ME. WE'LL BURY HIM TOMORROW. AND THEN YOU'LL BRING ME THE HERB. <<grief>>"
  opt "THEN I'LL BRING IT." -> dive

stage dive
  goal fetch "A THORNED GREY HERB" in cave
  then @t1
  journal "THE HERB OF UNDYING IS SAID TO GROW AT THE BOTTOM OF THE BLACK WATER IN {CAVE}. {LORD} OF {HOME} WANTS IT FOR {FRIEND}."

stage bottom
  talk lord
  say "IT'S REAL. IT'S REAL! GREY, AND THORNED, AND IT SMELLS LIKE A SPRING MORNING. ...BUT IT CAN'T WAKE {FRIEND}, CAN IT? I CAN SEE IT IN YOUR FACE. IT MAKES THE OLD YOUNG. IT DOESN'T RAISE THE DEAD."
  opt "EAT IT. LIVE FOREVER." -> eat
  opt "GIVE IT TO THE OLD OF {HOME}." -> share
  opt "LET IT GO." -> @t2

stage eat
  talk lord
  say "FOREVER. AND {FRIEND} IN THE GROUND. AND EVERYONE I KNOW AFTER HIM, ONE BY ONE, AND ME STILL HERE. ...NO. NO. I'LL CARRY IT HOME AND THINK ABOUT IT ON THE WAY. <<doubt>>"
  opt "THINK ON IT, THEN." -> @t2

stage share
  talk lord
  say "THE OLD OF {HOME}. {OLD}, THE BAKER, THE BLIND MAN AT THE GATE. YES. THAT'S WHAT HE'D DO. HE'D GIVE IT AWAY AND LAUGH. <<vow>>"
  do set gave 1
  opt "THEN LET'S CARRY IT HOME." -> @t2

stage serpent
  talk lord
  say "WE STOPPED TO DRINK AT THE POOL ON THE ROAD, AND I PUT THE HERB DOWN ON A STONE. A SNAKE CAME AND ATE IT, AND SHED ITS SKIN, AND WAS GONE. YOUNG AGAIN. A SNAKE. ...{PLAYER}, I'M LAUGHING. WHY AM I LAUGHING?"
  opt "BECAUSE HE WOULD HAVE." -> walls_end
  opt "BECAUSE IT'S OVER." -> walls_end
  opt "WE CAN DIVE AGAIN." -> again_end

stage walls_end
  end success
  say "{LORD} WENT HOME AND WEPT FOR {FRIEND} AT LAST, OUT LOUD, IN THE MARKETPLACE. THEN HE PUT THE MASONS TO WORK ON THE WALLS OF {HOME}. HE SAYS IT'S WHAT A MAN LEAVES INSTEAD OF HIMSELF."
  ?m_grief journal "THE HERB OF UNDYING WAS LOST. {LORD} MOURNED {FRIEND} AT LAST, AND IS BUILDING THE WALLS OF {HOME} IN HIS FRIEND'S NAME."
  !m_grief journal "THE HERB OF UNDYING WAS LOST TO A SNAKE. {LORD} IS BUILDING NEW WALLS FOR {HOME}, AND HAS STOPPED BEING AFRAID."
  do reward fair
  do remember lord "CLIMB THE WALL WITH ME. LOOK: THE BRICKWORK, THE GATES. HE'D HAVE MOCKED THE GATES. TOO FANCY, HE'D SAY. I KEPT THEM FANCY."
  do fact "{LORD} OF {HOME} LOST THE HERB OF UNDYING TO A SNAKE, AND BUILT WALLS INSTEAD, AND CARVED {FRIEND}'S NAME OVER THE GATE."
  do mark mourned_at_last

stage again_end
  end fail
  say "YOU DIVED AGAIN, AND AGAIN, AND THE BLACK WATER WAS EMPTY. {LORD} SAT ON THE BANK AND STOPPED LAUGHING. HE IS STILL LOOKING, THEY SAY. HE HAS STOPPED SHAVING AGAIN."
  journal "THE HERB WAS LOST, AND THERE WAS NO OTHER. {LORD} STILL SEARCHES, AND HAS NOT MOURNED {FRIEND}."
  do remember lord "THERE WILL BE ANOTHER. THERE'S ALWAYS ANOTHER. I DIVE EVERY MORNING. THE WATER IS VERY COLD."
)SAGA";

// ---------------------------------------------------------------- Baucis and Philemon
const char* const kGuestsUnknown = R"SAGA(
title [[THE GUESTS NOBODY TOOK IN|THE JUG THAT WOULD NOT EMPTY|TWO STRANGERS AT DUSK]]
hook npc farmer
pitch "[[pitch=WHO ARE YOUR GUESTS?|YOUR JUG LOOKS VERY FULL.|WHY DID YOU KILL YOUR GOOSE?]]"
hint "[[~pitch|TWO STRANGERS, RAGGED AS CROWS. EVERY DOOR IN TOWN SHUT IN THEIR FACES. OURS DIDN'T. WE'RE TOO POOR TO HAVE A GOOD DOOR.|THE JUG KEEPS FILLING. I POUR AND I POUR. MY WIFE WON'T LOOK AT IT.|TWO STRANGERS, RAGGED AS CROWS. EVERY DOOR IN TOWN SHUT IN THEIR FACES. OURS DIDN'T. WE'RE TOO POOR TO HAVE A GOOD DOOR.]]"
role giver giver
role home site home
role guest person [[male|female]] at home
role spouse resident spouse of giver
role neighbour resident any
var pleaded 0
slot t1 -> stranger price rival deceit world
slot t2 -> judgement mercy wonder prophecy

stage start
  talk giver
  say "TWO STRANGERS CAME AT DUSK. EVERY HOUSE IN {HOME} SHUT THEM OUT, EVEN THE PRIEST'S. WE GAVE THEM CABBAGE AND THE LAST OF THE BACON. AND THE JUG OF WINE KEEPS FILLING ITSELF, {PLAYER}. I'M FRIGHTENED. <<omen>>"
  opt "LET ME MEET THESE GUESTS." -> @t1
  opt "WHO SHUT THEM OUT?" -> neighbour_talk
  opt "A TRICK JUG. NOTHING MORE." -> refused

stage refused
  end fail
  say "PERHAPS. I'LL POUR ANOTHER CUP AND SEE. <<doubt>>"
  journal "YOU DISMISSED {GIVER}'S STRANGE GUESTS."
  do remember giver "THE GUESTS LEFT AT DAWN. THE JUG STILL FILLS. I DON'T DRINK FROM IT. I CAN'T BRING MYSELF TO."

stage neighbour_talk
  talk neighbour
  say "THOSE TWO? FILTHY. HALF-STARVED. COULD HAVE BEEN THIEVES, COULD HAVE BEEN SICK. I HAVE CHILDREN, {PLAYER}. YOU DON'T OPEN THE DOOR TO EVERY BEGGAR ON THE ROAD. <<refusal>>"
  opt "AND IF THEY WEREN'T BEGGARS?" -> @t1
  opt "FAIR. YOU HAVE CHILDREN." -> @t1

stage stranger
  talk guest
  say "SIT, TRAVELLER. YOU HAVE THE LOOK OF SOMEONE WHO'S BEEN TOLD WE'RE NOT WHAT WE SEEM. ...WE'RE NOT. WE WENT DOOR TO DOOR IN {HOME} TO SEE WHAT KIND OF PLACE IT IS. NOW WE KNOW. AT DAWN, {HOME} ANSWERS FOR IT."
  opt "SPARE THEM. THEY WERE AFRAID." -> plead
  opt "WHAT ABOUT {GIVER}?" -> spared
  opt "THEY EARNED IT." -> @t2

stage plead
  talk guest
  say "AFRAID. YES. FEAR SHUTS MORE DOORS THAN CRUELTY. ...YOU'RE THE SECOND TO PLEAD FOR THEM TONIGHT. THE OLD ONES ASKED THE SAME, OVER THE CABBAGE. <<proverb>>"
  do set pleaded 1
  opt "THEN LISTEN TO US." -> @t2

stage spared
  talk guest
  say "THE OLD ONES? THEY'LL COME UP THE HILL WITH US AT DAWN, AND NOT LOOK BACK. WE'LL GIVE THEM WHATEVER THEY ASK. ...ASK THEM, {PLAYER}. WE'RE CURIOUS WHAT TWO SUCH PEOPLE WANT."
  opt "I'LL ASK THEM." -> wish

stage wish
  talk giver
  say "WHAT WE WANT? WE'VE TALKED ABOUT IT FOR FORTY YEARS. WE WANT TO GO TOGETHER. THE SAME HOUR. SO NEITHER OF US EVER HAS TO BURY THE OTHER. THAT'S ALL. <<vow:love>>"
  opt "TELL THE GUESTS." -> @t2

stage judgement
  talk guest
  ?t2 say "DAWN. WE'VE HEARD YOU, AND THE OLD ONES, AND WHATEVER ELSE THIS NIGHT BROUGHT. NOW WE DECIDE WHAT {HOME} IS, AND YOU'LL STAND HERE WITH US WHILE WE DO."
  !t2 say "DAWN. WE'VE HEARD YOU, AND THE OLD ONES. NOW WE DECIDE WHAT {HOME} IS WORTH, AND YOU'LL STAND HERE WITH US ON THE HILL WHILE WE DO. SAY ONE LAST THING, IF YOU HAVE IT."
  opt "ONE GOOD HOUSE SAVES A TOWN." if var pleaded 1 -> mercy_end
  opt "LET {HOME} LEARN HUNGER." -> hunger_end
  opt "JUDGE THEM BY THE OLD ONES." -> mercy_end

stage mercy_end
  end success
  say "THE GUESTS WALKED DOWN THE HILL AND WERE NOT THERE. {HOME} WOKE AS IT ALWAYS DOES. THE POOR COTTAGE HAS A ROOF OF GOLD THATCH NOW, AND BY ITS DOOR TWO TREES GROW, AN OAK AND A LIME, WITH THEIR BRANCHES TWINED."
  journal "THE STRANGE GUESTS SPARED {HOME} FOR THE SAKE OF ONE KIND HOUSE. TWO TREES GROW BY {GIVER}'S DOOR."
  do reward fair
  do remember giver "THE JUG STOPPED FILLING THIS MORNING. I'M ALMOST SORRY. THERE ARE TWO SAPLINGS BY THE DOOR. MY WIFE WATERS ONE AND I WATER THE OTHER."
  do fact "TWO STRANGERS WERE TURNED FROM EVERY DOOR IN {HOME} BUT ONE. THEY SPARED THE TOWN FOR IT. NOW {HOME} OPENS ITS DOORS AT DUSK."
  do mark guests_received

stage hunger_end
  end success
  say "WHEN {HOME} WOKE, ITS GRANARIES WERE FULL OF MICE AND ITS WELLS TASTED OF SALT. ONLY THE POOR COTTAGE ON THE HILL HAD BREAD. {GIVER} GAVE IT ALL AWAY BY NOON, OF COURSE."
  journal "THE STRANGE GUESTS SENT HUNGER ON {HOME} FOR ITS SHUT DOORS. {GIVER}'S HOUSE ALONE WAS SPARED."
  do realm famine home
  do reward small
  do remember neighbour "THE MICE TOOK EVERYTHING. EVERYTHING! AND THE OLD FOOL ON THE HILL FED MY CHILDREN. I'LL NEVER SHUT MY DOOR AGAIN. NEVER."
  do fact "A HUNGER FELL ON {HOME} THE MORNING AFTER IT SHUT EVERY DOOR ON TWO RAGGED STRANGERS. ONLY ONE HOUSE THAT TOOK THEM IN HAD BREAD."
)SAGA";

struct Def {
  const char* id;
  const char* name;
  uint32_t themes;
  uint32_t needs;
  uint16_t motives;
  uint32_t twists;
  const char* body;
};

uint16_t M(Motive a) { return motiveBit(a); }

}  // namespace

void addMyth(std::vector<Archetype>& v) {
  const Def defs[] = {
      {"do_not_look", "THE SINGER WHO WENT DOWN", TH_LOVE | TH_GRIEF | TH_FAITH | TH_TEMPTATION | TH_WONDER, N_RUIN,
       (uint16_t)(M(Motive::Love) | M(Motive::Grief) | M(Motive::Hope)),
       TF_PRICE | TF_MERCY | TF_IDENTITY | TF_BETRAYAL | TF_WONDER | TF_PROPHECY | TF_RETURN, kDoNotLook},
      {"set_labours", "THE LABOURS SET TO BREAK YOU", TH_REDEMPTION | TH_COURAGE | TH_JUDGEMENT | TH_SACRIFICE, N_RUIN | N_CAVE,
       (uint16_t)(M(Motive::Duty) | M(Motive::Shame) | M(Motive::Fear)),
       TF_RIVAL | TF_BETRAYAL | TF_DECEIT | TF_PRICE | TF_MERCY | TF_PROPHECY | TF_WONDER | TF_WORLD, kSetLabours},
      {"long_way_home", "THE LONG ROAD HOME", TH_HOMECOMING | TH_LOYALTY | TH_LOVE | TH_TEMPTATION | TH_VENGEANCE, N_TOWN,
       (uint16_t)(M(Motive::Hope) | M(Motive::Love) | M(Motive::Duty) | M(Motive::Grief)),
       TF_WONDER | TF_BETRAYAL | TF_PRICE | TF_WORLD | TF_MERCY | TF_RIVAL | TF_IDENTITY | TF_DECEIT, kLongWayHome},
      {"stolen_fire", "THE FIRE FROM THE MOUNTAIN", TH_SACRIFICE | TH_FREEDOM | TH_JUDGEMENT | TH_PRIDE, N_CAVE | N_SMITH,
       (uint16_t)(M(Motive::Pride) | M(Motive::Devotion) | M(Motive::Love) | M(Motive::Duty)),
       TF_PRICE | TF_BETRAYAL | TF_DECEIT | TF_RIVAL | TF_MERCY | TF_WONDER | TF_PROPHECY | TF_WORLD, kStolenFire},
      {"twilight_doom", "THE DOOM FORETOLD", TH_DOOM | TH_PROPHECY | TH_COURAGE | TH_SACRIFICE | TH_WAR, N_BOSS | N_TOWN,
       (uint16_t)(M(Motive::Fear) | M(Motive::Duty) | M(Motive::Devotion) | M(Motive::Hope)),
       TF_RIVAL | TF_BETRAYAL | TF_PROPHECY | TF_PRICE | TF_WONDER | TF_WORLD | TF_RETURN | TF_MERCY | TF_IDENTITY, kTwilightDoom},
      {"trickster_bound", "THE TRICKSTER BOUND", TH_TRICKERY | TH_JUDGEMENT | TH_GRIEF | TH_MERCY | TH_LOVE, N_CAVE,
       (uint16_t)(M(Motive::Grief) | M(Motive::Vengeance) | M(Motive::Love) | M(Motive::Shame)),
       TF_BETRAYAL | TF_DECEIT | TF_PRICE | TF_RIVAL | TF_MERCY | TF_WONDER | TF_PROPHECY, kTricksterBound},
      {"undying_herb", "THE HERB OF UNDYING", TH_GRIEF | TH_FRIENDSHIP | TH_PRIDE | TH_TEMPTATION | TH_DOOM, N_CAVE,
       (uint16_t)(M(Motive::Fear) | M(Motive::Grief) | M(Motive::Duty) | M(Motive::Love)),
       TF_PRICE | TF_WONDER | TF_BETRAYAL | TF_RIVAL | TF_WORLD | TF_MERCY | TF_PROPHECY | TF_DECEIT, kUndyingHerb},
      {"guests_unknown", "THE GUESTS NOBODY TOOK IN", TH_HOSPITALITY | TH_JUDGEMENT | TH_LOVE | TH_WONDER | TH_MERCY, N_VILLAGE,
       (uint16_t)(M(Motive::Fear) | M(Motive::Love) | M(Motive::Devotion) | M(Motive::Hope)),
       TF_PRICE | TF_RIVAL | TF_DECEIT | TF_WORLD | TF_MERCY | TF_WONDER | TF_PROPHECY, kGuestsUnknown},
  };
  for (const Def& d : defs) {
    Archetype a;
    a.id = d.id;
    a.name = d.name;
    a.source = Source::Myth;
    a.themes = d.themes;
    a.needs = d.needs;
    a.tier = 2;
    a.motives = d.motives;
    a.twists = d.twists;
    a.body = d.body;
    v.push_back(a);
  }
}

}  // namespace arch
}  // namespace saga
}  // namespace story
